name: spire-codex-beta

services:
  backend:
    image: ptrlrd/spire-codex-backend:beta
    container_name: spire-codex-beta-backend
    volumes:
      - ./data-beta:/data
      - ./.secrets:/secrets:ro
    environment:
      - DATA_DIR=/data
      - FEEDBACK_WEBHOOK_URL=${FEEDBACK_WEBHOOK_URL:-}
      - GUIDE_WEBHOOK_URL=${GUIDE_WEBHOOK_URL:-}
      - DISABLE_RUN_SUBMISSIONS=1
      - SENTRY_DSN=${SENTRY_DSN:-}
      - GITHUB_APP_ID=${GITHUB_APP_ID:-}
      - GITHUB_APP_INSTALLATION_ID=${GITHUB_APP_INSTALLATION_ID:-}
      - GITHUB_APP_REPO=${GITHUB_APP_REPO:-}
      - GITHUB_APP_PRIVATE_KEY_PATH=${GITHUB_APP_PRIVATE_KEY_PATH:-/secrets/knowledge-demon.private-key.pem}
    networks:
      - nginx_web-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  frontend:
    image: ptrlrd/spire-codex-frontend:beta
    container_name: spire-codex-beta-frontend
    depends_on:
      - backend
    volumes:
      - ./data-beta:/data:ro
    environment:
      - API_INTERNAL_URL=http://spire-codex-beta-backend:8000
      - NEXT_PUBLIC_SITE_URL=https://beta.spire-codex.com
    networks:
      - nginx_web-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

networks:
  nginx_web-network:
    external: true
