# Litestream config for spire-codex prod origins.
#
# DO NOT EDIT THIS FILE ON THE HOST. It's rendered from this template
# in the repo + 1Password secrets via:
#
#   ./bin/op-ansible playbooks/sync-litestream.yml --limit primary
#
# The credentials below are 1Password references that `op inject`
# resolves at render time, so the values never live in git. The
# rendered file on the host is plaintext (Litestream can't read 1P
# references natively), so it stays at 0600 root:root behind file
# perms.
#
# Why only primary? Secondary's Litestream was never running, and both
# hosts pointed at the same B2 bucket/path anyway (would clobber each
# other). After Turso cutover, Litestream goes away entirely.

dbs:
  - path: /var/www/spire-codex/data/runs.db
    replicas:
      - type: s3
        bucket: spire-codex
        path: runs.db
        endpoint: https://s3.us-west-004.backblazeb2.com
        access-key-id: op://Spire Codex/Backblaze/rw-keyId
        secret-access-key: op://Spire Codex/Backblaze/rw-applicationKey
