// Auto-added UI translations (batch 9c): the replay viewer saying what the journal did and did not record.
export const X9C: Record<string, Record<string, string>> = {
  "Chosen option not recorded": { eng: "Chosen option not recorded", deu: "Gewählte Option nicht aufgezeichnet", esp: "La opción elegida no se registró", fra: "Option choisie non enregistrée", ita: "Opzione scelta non registrata", jpn: "選択した項目は記録されていません", kor: "선택한 항목이 기록되지 않음", pol: "Nie zapisano wybranej opcji", ptb: "A opção escolhida não foi registrada", rus: "Выбранный вариант не записан", spa: "La opción elegida no se registró", tha: "ไม่ได้บันทึกตัวเลือกที่เลือก", tur: "Seçilen seçenek kaydedilmedi", zhs: "未记录所选选项", zht: "未記錄所選選項" },
  "Some picks not recorded": { eng: "Some picks not recorded", deu: "Einige Auswahlen nicht aufgezeichnet", esp: "Algunas elecciones no se registraron", fra: "Certains choix non enregistrés", ita: "Alcune scelte non registrate", jpn: "一部の選択は記録されていません", kor: "일부 선택이 기록되지 않음", pol: "Nie zapisano części wyborów", ptb: "Algumas escolhas não foram registradas", rus: "Часть выборов не записана", spa: "Algunas elecciones no se registraron", tha: "ไม่ได้บันทึกบางตัวเลือก", tur: "Bazı seçimler kaydedilmedi", zhs: "部分选择未被记录", zht: "部分選擇未被記錄" },
  "Conflicting choice records": { eng: "Conflicting choice records", deu: "Widersprüchliche Auswahleinträge", esp: "Registros de elección contradictorios", fra: "Enregistrements de choix contradictoires", ita: "Registrazioni di scelta contraddittorie", jpn: "選択の記録が矛盾しています", kor: "선택 기록이 서로 어긋남", pol: "Sprzeczne zapisy wyboru", ptb: "Registros de escolha contraditórios", rus: "Противоречивые записи выбора", spa: "Registros de elección contradictorios", tha: "บันทึกการเลือกขัดแย้งกัน", tur: "Çelişkili seçim kayıtları", zhs: "选择记录相互矛盾", zht: "選擇記錄相互矛盾" },
  "This recording did not include map positions.": { eng: "This recording did not include map positions.", deu: "Diese Aufzeichnung enthielt keine Kartenpositionen.", esp: "Esta grabación no incluyó posiciones en el mapa.", fra: "Cet enregistrement ne contenait pas de positions sur la carte.", ita: "Questa registrazione non includeva le posizioni sulla mappa.", jpn: "この記録にはマップ上の位置が含まれていません。", kor: "이 기록에는 지도 위치가 포함되지 않았습니다.", pol: "Ten zapis nie zawierał pozycji na mapie.", ptb: "Esta gravação não incluiu posições no mapa.", rus: "В этой записи нет позиций на карте.", spa: "Esta grabación no incluyó posiciones en el mapa.", tha: "การบันทึกนี้ไม่มีตำแหน่งบนแผนที่", tur: "Bu kayıt harita konumlarını içermiyordu.", zhs: "此记录未包含地图位置。", zht: "此記錄未包含地圖位置。" },
  "Fight {n} of {of}": { eng: "Fight {n} of {of}", deu: "Kampf {n} von {of}", esp: "Combate {n} de {of}", fra: "Combat {n} sur {of}", ita: "Combattimento {n} di {of}", jpn: "戦闘 {n}/{of}", kor: "전투 {n}/{of}", pol: "Walka {n} z {of}", ptb: "Combate {n} de {of}", rus: "Бой {n} из {of}", spa: "Combate {n} de {of}", tha: "การต่อสู้ที่ {n} จาก {of}", tur: "{of} savaştan {n}. si", zhs: "第 {n} 场战斗，共 {of} 场", zht: "第 {n} 場戰鬥，共 {of} 場" },
  "Result not recorded": { eng: "Result not recorded", deu: "Ergebnis nicht aufgezeichnet", esp: "Resultado no registrado", fra: "Résultat non enregistré", ita: "Esito non registrato", jpn: "結果は記録されていません", kor: "결과가 기록되지 않음", pol: "Nie zapisano wyniku", ptb: "Resultado não registrado", rus: "Результат не записан", spa: "Resultado no registrado", tha: "ไม่ได้บันทึกผลลัพธ์", tur: "Sonuç kaydedilmedi", zhs: "未记录结果", zht: "未記錄結果" },
  "End not recorded": { eng: "End not recorded", deu: "Ende nicht aufgezeichnet", esp: "Final no registrado", fra: "Fin non enregistrée", ita: "Fine non registrata", jpn: "終了は記録されていません", kor: "종료가 기록되지 않음", pol: "Nie zapisano zakończenia", ptb: "Fim não registrado", rus: "Окончание не записано", spa: "Final no registrado", tha: "ไม่ได้บันทึกการจบ", tur: "Bitiş kaydedilmedi", zhs: "未记录结束", zht: "未記錄結束" },
  "Damage per floor": { eng: "Damage per floor", deu: "Schaden pro Ebene", esp: "Daño por piso", fra: "Dégâts par étage", ita: "Danni per piano", jpn: "フロアごとのダメージ", kor: "층별 피해", pol: "Obrażenia na piętro", ptb: "Dano por andar", rus: "Урон за этаж", spa: "Daño por piso", tha: "ความเสียหายต่อชั้น", tur: "Kat başına hasar", zhs: "每层伤害", zht: "每層傷害" },
  "Turns per floor": { eng: "Turns per floor", deu: "Züge pro Ebene", esp: "Turnos por piso", fra: "Tours par étage", ita: "Turni per piano", jpn: "フロアごとのターン数", kor: "층별 턴 수", pol: "Tury na piętro", ptb: "Turnos por andar", rus: "Ходов за этаж", spa: "Turnos por piso", tha: "จำนวนเทิร์นต่อชั้น", tur: "Kat başına tur", zhs: "每层回合数", zht: "每層回合數" },
  "HP lost": { eng: "HP lost", deu: "LP verloren", esp: "PS perdidos", fra: "PV perdus", ita: "PF persi", jpn: "HP損失", kor: "잃은 체력", pol: "Utracone PŻ", ptb: "PV perdidos", rus: "Потеряно ОЗ", spa: "PS perdidos", tha: "HP ที่เสียไป", tur: "Kaybedilen CP", zhs: "损失生命", zht: "損失生命" },
  "HP lost unknown": { eng: "HP lost unknown", deu: "LP-Verlust unbekannt", esp: "PS perdidos desconocidos", fra: "PV perdus inconnus", ita: "PF persi sconosciuti", jpn: "HP損失は不明", kor: "잃은 체력 알 수 없음", pol: "Utrata PŻ nieznana", ptb: "PV perdidos desconhecidos", rus: "Потеря ОЗ неизвестна", spa: "PS perdidos desconocidos", tha: "ไม่ทราบ HP ที่เสียไป", tur: "Kaybedilen CP bilinmiyor", zhs: "损失生命未知", zht: "損失生命未知" },
  "HP lost per floor": { eng: "HP lost per floor", deu: "LP-Verlust pro Ebene", esp: "PS perdidos por piso", fra: "PV perdus par étage", ita: "PF persi per piano", jpn: "フロアごとのHP損失", kor: "층별 잃은 체력", pol: "Utrata PŻ na piętro", ptb: "PV perdidos por andar", rus: "Потеря ОЗ за этаж", spa: "PS perdidos por piso", tha: "HP ที่เสียต่อชั้น", tur: "Kat başına kaybedilen CP", zhs: "每层损失生命", zht: "每層損失生命" },
  "Floors with no recorded position: {n}": { eng: "Floors with no recorded position: {n}", deu: "Ebenen ohne aufgezeichnete Position: {n}", esp: "Pisos sin posición registrada: {n}", fra: "Étages sans position enregistrée : {n}", ita: "Piani senza posizione registrata: {n}", jpn: "位置が記録されていないフロア: {n}", kor: "위치가 기록되지 않은 층: {n}", pol: "Piętra bez zapisanej pozycji: {n}", ptb: "Andares sem posição registrada: {n}", rus: "Этажей без записанной позиции: {n}", spa: "Pisos sin posición registrada: {n}", tha: "ชั้นที่ไม่มีตำแหน่งบันทึกไว้: {n}", tur: "Kayıtlı konumu olmayan katlar: {n}", zhs: "没有记录位置的层数：{n}", zht: "沒有記錄位置的層數：{n}" },
  "Recorded positions not on the map: {n}": { eng: "Recorded positions not on the map: {n}", deu: "Aufgezeichnete Positionen außerhalb der Karte: {n}", esp: "Posiciones registradas fuera del mapa: {n}", fra: "Positions enregistrées hors de la carte : {n}", ita: "Posizioni registrate fuori dalla mappa: {n}", jpn: "マップ上にない記録位置: {n}", kor: "지도에 없는 기록된 위치: {n}", pol: "Zapisane pozycje spoza mapy: {n}", ptb: "Posições registradas fora do mapa: {n}", rus: "Записанных позиций вне карты: {n}", spa: "Posiciones registradas fuera del mapa: {n}", tha: "ตำแหน่งที่บันทึกไว้ซึ่งไม่อยู่บนแผนที่: {n}", tur: "Haritada olmayan kayıtlı konumlar: {n}", zhs: "不在地图上的记录位置：{n}", zht: "不在地圖上的記錄位置：{n}" },
};
