// Auto-added UI translations (batch 9a): bulk run deletion and the admin hide toggle.
export const X9A: Record<string, Record<string, string>> = {
  "Select all": { eng: "Select all", deu: "Alle auswählen", esp: "Seleccionar todo", fra: "Tout sélectionner", ita: "Seleziona tutto", jpn: "すべて選択", kor: "전체 선택", pol: "Zaznacz wszystko", ptb: "Selecionar tudo", rus: "Выбрать все", spa: "Seleccionar todo", tha: "เลือกทั้งหมด", tur: "Tümünü seç", zhs: "全选", zht: "全選" },
  "Select this run": { eng: "Select this run", deu: "Diesen Run auswählen", esp: "Seleccionar esta partida", fra: "Sélectionner cette partie", ita: "Seleziona questa partita", jpn: "このランを選択", kor: "이 런 선택", pol: "Zaznacz ten przebieg", ptb: "Selecionar esta partida", rus: "Выбрать этот забег", spa: "Seleccionar esta partida", tha: "เลือกรันนี้", tur: "Bu koşuyu seç", zhs: "选择此对局", zht: "選擇此對局" },
  "Select every run on this page": { eng: "Select every run on this page", deu: "Alle Runs auf dieser Seite auswählen", esp: "Seleccionar todas las partidas de esta página", fra: "Sélectionner toutes les parties de cette page", ita: "Seleziona tutte le partite di questa pagina", jpn: "このページのすべてのランを選択", kor: "이 페이지의 모든 런 선택", pol: "Zaznacz wszystkie przebiegi na tej stronie", ptb: "Selecionar todas as partidas desta página", rus: "Выбрать все забеги на этой странице", spa: "Seleccionar todas las partidas de esta página", tha: "เลือกทุกรันในหน้านี้", tur: "Bu sayfadaki tüm koşuları seç", zhs: "选择本页所有对局", zht: "選擇本頁所有對局" },
  "{n} selected": { eng: "{n} selected", deu: "{n} ausgewählt", esp: "{n} seleccionadas", fra: "{n} sélectionnées", ita: "{n} selezionate", jpn: "{n}件選択中", kor: "{n}개 선택됨", pol: "Zaznaczono {n}", ptb: "{n} selecionadas", rus: "Выбрано: {n}", spa: "{n} seleccionadas", tha: "เลือกแล้ว {n} รายการ", tur: "{n} seçildi", zhs: "已选择 {n} 个", zht: "已選擇 {n} 個" },
  "Delete selected": { eng: "Delete selected", deu: "Auswahl löschen", esp: "Eliminar seleccionadas", fra: "Supprimer la sélection", ita: "Elimina selezionate", jpn: "選択したものを削除", kor: "선택 항목 삭제", pol: "Usuń zaznaczone", ptb: "Excluir selecionadas", rus: "Удалить выбранные", spa: "Eliminar seleccionadas", tha: "ลบรายการที่เลือก", tur: "Seçilenleri sil", zhs: "删除所选", zht: "刪除所選" },
  "Delete {n} runs": { eng: "Delete {n} runs", deu: "{n} Runs löschen", esp: "Eliminar {n} partidas", fra: "Supprimer {n} parties", ita: "Elimina {n} partite", jpn: "{n}件のランを削除", kor: "런 {n}개 삭제", pol: "Usuń {n} przebiegów", ptb: "Excluir {n} partidas", rus: "Удалить {n} забегов", spa: "Eliminar {n} partidas", tha: "ลบ {n} รัน", tur: "{n} koşuyu sil", zhs: "删除 {n} 个对局", zht: "刪除 {n} 個對局" },
  "Deleting...": { eng: "Deleting...", deu: "Wird gelöscht...", esp: "Eliminando...", fra: "Suppression...", ita: "Eliminazione...", jpn: "削除中...", kor: "삭제 중...", pol: "Usuwanie...", ptb: "Excluindo...", rus: "Удаление...", spa: "Eliminando...", tha: "กำลังลบ...", tur: "Siliniyor...", zhs: "正在删除...", zht: "正在刪除..." },
  "Removed {n} runs from your profile": { eng: "Removed {n} runs from your profile", deu: "{n} Runs aus deinem Profil entfernt", esp: "Se han quitado {n} partidas de tu perfil", fra: "{n} parties retirées de votre profil", ita: "Rimosse {n} partite dal tuo profilo", jpn: "{n}件のランをプロフィールから削除しました", kor: "프로필에서 런 {n}개를 제거했습니다", pol: "Usunięto {n} przebiegów z twojego profilu", ptb: "{n} partidas removidas do seu perfil", rus: "Из вашего профиля удалено забегов: {n}", spa: "Se han quitado {n} partidas de tu perfil", tha: "นำ {n} รันออกจากโปรไฟล์ของคุณแล้ว", tur: "Profilinizden {n} koşu kaldırıldı", zhs: "已从你的个人资料中移除 {n} 个对局", zht: "已從你的個人檔案中移除 {n} 個對局" },
  "Removed {n} runs, {failed} could not be removed": { eng: "Removed {n} runs, {failed} could not be removed", deu: "{n} Runs entfernt, {failed} konnten nicht entfernt werden", esp: "Se han quitado {n} partidas; {failed} no se pudieron quitar", fra: "{n} parties retirées, {failed} n'ont pas pu l'être", ita: "Rimosse {n} partite, {failed} non è stato possibile rimuoverle", jpn: "{n}件のランを削除しました。{failed}件は削除できませんでした", kor: "런 {n}개를 제거했고 {failed}개는 제거하지 못했습니다", pol: "Usunięto {n} przebiegów, {failed} nie udało się usunąć", ptb: "{n} partidas removidas, {failed} não puderam ser removidas", rus: "Удалено забегов: {n}, не удалось удалить: {failed}", spa: "Se han quitado {n} partidas; {failed} no se pudieron quitar", tha: "นำออก {n} รัน และไม่สามารถนำออกได้ {failed} รัน", tur: "{n} koşu kaldırıldı, {failed} tanesi kaldırılamadı", zhs: "已移除 {n} 个对局，{failed} 个无法移除", zht: "已移除 {n} 個對局，{failed} 個無法移除" },
  "Unhide": { eng: "Unhide", deu: "Einblenden", esp: "Mostrar", fra: "Réafficher", ita: "Mostra", jpn: "再表示", kor: "숨김 해제", pol: "Odkryj", ptb: "Reexibir", rus: "Показать", spa: "Mostrar", tha: "เลิกซ่อน", tur: "Göster", zhs: "取消隐藏", zht: "取消隱藏" },
  "Run hidden": { eng: "Run hidden", deu: "Run ausgeblendet", esp: "Partida oculta", fra: "Partie masquée", ita: "Partita nascosta", jpn: "ランを非表示にしました", kor: "런을 숨겼습니다", pol: "Przebieg ukryty", ptb: "Partida ocultada", rus: "Забег скрыт", spa: "Partida oculta", tha: "ซ่อนรันแล้ว", tur: "Koşu gizlendi", zhs: "对局已隐藏", zht: "對局已隱藏" },
  "Run unhidden": { eng: "Run unhidden", deu: "Run wieder eingeblendet", esp: "Partida visible de nuevo", fra: "Partie réaffichée", ita: "Partita di nuovo visibile", jpn: "ランを再表示しました", kor: "런 숨김을 해제했습니다", pol: "Przebieg ponownie widoczny", ptb: "Partida reexibida", rus: "Забег снова виден", spa: "Partida visible de nuevo", tha: "เลิกซ่อนรันแล้ว", tur: "Koşu tekrar görünür", zhs: "对局已取消隐藏", zht: "對局已取消隱藏" },
  "Failed to update this run": { eng: "Failed to update this run", deu: "Der Run konnte nicht aktualisiert werden", esp: "No se pudo actualizar esta partida", fra: "Impossible de mettre à jour cette partie", ita: "Impossibile aggiornare questa partita", jpn: "このランを更新できませんでした", kor: "이 런을 업데이트하지 못했습니다", pol: "Nie udało się zaktualizować tego przebiegu", ptb: "Não foi possível atualizar esta partida", rus: "Не удалось обновить этот забег", spa: "No se pudo actualizar esta partida", tha: "อัปเดตรันนี้ไม่สำเร็จ", tur: "Bu koşu güncellenemedi", zhs: "无法更新此对局", zht: "無法更新此對局" },
};
