// Auto-added UI translations (batch 9c): the replay viewer saying what the journal did and did not record.
export const X9C: Record<string, Record<string, string>> = {
  "Chosen option not recorded": { eng: "Chosen option not recorded", deu: "Gewählte Option nicht aufgezeichnet", esp: "La opción elegida no se registró", fra: "Option choisie non enregistrée", ita: "Opzione scelta non registrata", jpn: "選択した項目は記録されていません", kor: "선택한 항목이 기록되지 않음", pol: "Nie zapisano wybranej opcji", ptb: "A opção escolhida não foi registrada", rus: "Выбранный вариант не записан", spa: "La opción elegida no se registró", tha: "ไม่ได้บันทึกตัวเลือกที่เลือก", tur: "Seçilen seçenek kaydedilmedi", zhs: "未记录所选选项", zht: "未記錄所選選項" },
  "Some picks not recorded": { eng: "Some picks not recorded", deu: "Einige Auswahlen nicht aufgezeichnet", esp: "Algunas elecciones no se registraron", fra: "Certains choix non enregistrés", ita: "Alcune scelte non registrate", jpn: "一部の選択は記録されていません", kor: "일부 선택이 기록되지 않음", pol: "Nie zapisano części wyborów", ptb: "Algumas escolhas não foram registradas", rus: "Часть выборов не записана", spa: "Algunas elecciones no se registraron", tha: "ไม่ได้บันทึกบางตัวเลือก", tur: "Bazı seçimler kaydedilmedi", zhs: "部分选择未被记录", zht: "部分選擇未被記錄" },
  "Conflicting choice records": { eng: "Conflicting choice records", deu: "Widersprüchliche Auswahleinträge", esp: "Registros de elección contradictorios", fra: "Enregistrements de choix contradictoires", ita: "Registrazioni di scelta contraddittorie", jpn: "選択の記録が矛盾しています", kor: "선택 기록이 서로 어긋남", pol: "Sprzeczne zapisy wyboru", ptb: "Registros de escolha contraditórios", rus: "Противоречивые записи выбора", spa: "Registros de elección contradictorios", tha: "บันทึกการเลือกขัดแย้งกัน", tur: "Çelişkili seçim kayıtları", zhs: "选择记录相互矛盾", zht: "選擇記錄相互矛盾" },
  "This recording did not include map positions.": { eng: "This recording did not include map positions.", deu: "Diese Aufzeichnung enthielt keine Kartenpositionen.", esp: "Esta grabación no incluyó posiciones en el mapa.", fra: "Cet enregistrement ne contenait pas de positions sur la carte.", ita: "Questa registrazione non includeva le posizioni sulla mappa.", jpn: "この記録にはマップ上の位置が含まれていません。", kor: "이 기록에는 지도 위치가 포함되지 않았습니다.", pol: "Ten zapis nie zawierał pozycji na mapie.", ptb: "Esta gravação não incluiu posições no mapa.", rus: "В этой записи нет позиций на карте.", spa: "Esta grabación no incluyó posiciones en el mapa.", tha: "การบันทึกนี้ไม่มีตำแหน่งบนแผนที่", tur: "Bu kayıt harita konumlarını içermiyordu.", zhs: "此记录未包含地图位置。", zht: "此記錄未包含地圖位置。" },
  "{n} floors on this act have no recorded position.": { eng: "{n} floors on this act have no recorded position.", deu: "Für {n} Ebenen dieses Akts wurde keine Position aufgezeichnet.", esp: "{n} pisos de este acto no tienen posición registrada.", fra: "{n} étages de cet acte n'ont pas de position enregistrée.", ita: "{n} piani di questo atto non hanno una posizione registrata.", jpn: "この幕の{n}フロアには位置が記録されていません。", kor: "이 막의 {n}개 층에는 기록된 위치가 없습니다.", pol: "{n} pięter tego aktu nie ma zapisanej pozycji.", ptb: "{n} andares deste ato não têm posição registrada.", rus: "Для {n} этажей этого акта позиция не записана.", spa: "{n} pisos de este acto no tienen posición registrada.", tha: "{n} ชั้นในองก์นี้ไม่มีตำแหน่งที่บันทึกไว้", tur: "Bu perdedeki {n} katın kayıtlı konumu yok.", zhs: "本幕有 {n} 层没有记录位置。", zht: "本幕有 {n} 層沒有記錄位置。" },
  "{n} recorded positions are not on the recorded map.": { eng: "{n} recorded positions are not on the recorded map.", deu: "{n} aufgezeichnete Positionen liegen nicht auf der aufgezeichneten Karte.", esp: "{n} posiciones registradas no están en el mapa registrado.", fra: "{n} positions enregistrées ne figurent pas sur la carte enregistrée.", ita: "{n} posizioni registrate non sono sulla mappa registrata.", jpn: "記録された位置のうち{n}件は記録されたマップ上にありません。", kor: "기록된 위치 {n}개가 기록된 지도에 없습니다.", pol: "{n} zapisanych pozycji nie ma na zapisanej mapie.", ptb: "{n} posições registradas não estão no mapa registrado.", rus: "{n} записанных позиций отсутствуют на записанной карте.", spa: "{n} posiciones registradas no están en el mapa registrado.", tha: "ตำแหน่งที่บันทึกไว้ {n} จุดไม่อยู่บนแผนที่ที่บันทึกไว้", tur: "Kaydedilen {n} konum, kaydedilen haritada yok.", zhs: "有 {n} 个记录位置不在记录的地图上。", zht: "有 {n} 個記錄位置不在記錄的地圖上。" },
};
