/**
 * UI string translations for non-game-data text across the site.
 * Every key MUST have an "eng" entry — that's the fallback.
 */

const UI: Record<string, Record<string, string>> = {
  // Tabs
  "Overview":        { eng: "Overview", deu: "Übersicht", esp: "Resumen", fra: "Aperçu", ita: "Panoramica", jpn: "概要", kor: "개요", pol: "Przegląd", ptb: "Visão geral", rus: "Обзор", spa: "Resumen", tha: "ภาพรวม", tur: "Genel Bakış", zhs: "概览" },
  "Details":         { eng: "Details", deu: "Details", esp: "Detalles", fra: "Détails", ita: "Dettagli", jpn: "詳細", kor: "상세", pol: "Szczegóły", ptb: "Detalhes", rus: "Детали", spa: "Detalles", tha: "รายละเอียด", tur: "Detaylar", zhs: "详情" },
  "Info":            { eng: "Info", deu: "Info", esp: "Info", fra: "Info", ita: "Info", jpn: "情報", kor: "정보", pol: "Info", ptb: "Info", rus: "Инфо", spa: "Info", tha: "ข้อมูล", tur: "Bilgi", zhs: "信息" },

  // Navigation
  "Back to":         { eng: "Back to", deu: "Zurück zu", esp: "Volver a", fra: "Retour à", ita: "Torna a", jpn: "戻る：", kor: "돌아가기:", pol: "Powrót do", ptb: "Voltar para", rus: "Назад к", spa: "Volver a", tha: "กลับไป", tur: "Geri dön:", zhs: "返回" },
  "Home":            { eng: "Home", deu: "Startseite", esp: "Inicio", fra: "Accueil", ita: "Home", jpn: "ホーム", kor: "홈", pol: "Strona główna", ptb: "Início", rus: "Главная", spa: "Inicio", tha: "หน้าแรก", tur: "Ana Sayfa", zhs: "首页" },

  // Search & filters
  "Search...":       { eng: "Search...", deu: "Suchen...", esp: "Buscar...", fra: "Rechercher...", ita: "Cerca...", jpn: "検索...", kor: "검색...", pol: "Szukaj...", ptb: "Pesquisar...", rus: "Поиск...", spa: "Buscar...", tha: "ค้นหา...", tur: "Ara...", zhs: "搜索..." },
  "All Colors":      { eng: "All Colors", deu: "Alle Farben", esp: "Todos los colores", fra: "Toutes les couleurs", ita: "Tutti i colori", jpn: "すべての色", kor: "모든 색상", pol: "Wszystkie kolory", ptb: "Todas as cores", rus: "Все цвета", spa: "Todos los colores", tha: "ทุกสี", tur: "Tüm Renkler", zhs: "所有颜色" },
  "All Types":       { eng: "All Types", deu: "Alle Typen", esp: "Todos los tipos", fra: "Tous les types", ita: "Tutti i tipi", jpn: "すべてのタイプ", kor: "모든 유형", pol: "Wszystkie typy", ptb: "Todos os tipos", rus: "Все типы", spa: "Todos los tipos", tha: "ทุกประเภท", tur: "Tüm Türler", zhs: "所有类型" },
  "All Rarities":    { eng: "All Rarities", deu: "Alle Seltenheiten", esp: "Todas las rarezas", fra: "Toutes les raretés", ita: "Tutte le rarità", jpn: "すべてのレアリティ", kor: "모든 희귀도", pol: "Wszystkie rzadkości", ptb: "Todas as raridades", rus: "Все редкости", spa: "Todas las rarezas", tha: "ทุกความหายาก", tur: "Tüm Nadirlikler", zhs: "所有稀有度" },
  "All Keywords":    { eng: "All Keywords", deu: "Alle Schlüsselwörter", esp: "Todas las palabras clave", fra: "Tous les mots-clés", ita: "Tutte le parole chiave", jpn: "すべてのキーワード", kor: "모든 키워드", pol: "Wszystkie słowa kluczowe", ptb: "Todas as palavras-chave", rus: "Все ключевые слова", spa: "Todas las palabras clave", tha: "คีย์เวิร์ดทั้งหมด", tur: "Tüm Anahtar Kelimeler", zhs: "所有关键词" },
  "All Pools":       { eng: "All Pools", deu: "Alle Pools", esp: "Todos los grupos", fra: "Tous les groupes", ita: "Tutti i gruppi", jpn: "すべてのプール", kor: "모든 풀", pol: "Wszystkie pule", ptb: "Todos os grupos", rus: "Все группы", spa: "Todos los grupos", tha: "ทุกกลุ่ม", tur: "Tüm Havuzlar", zhs: "所有池" },
  "All Characters":  { eng: "All Characters", deu: "Alle Charaktere", esp: "Todos los personajes", fra: "Tous les personnages", ita: "Tutti i personaggi", jpn: "すべてのキャラクター", kor: "모든 캐릭터", pol: "Wszystkie postacie", ptb: "Todos os personagens", rus: "Все персонажи", spa: "Todos los personajes", tha: "ตัวละครทั้งหมด", tur: "Tüm Karakterler", zhs: "所有角色" },
  "results":         { eng: "results", deu: "Ergebnisse", esp: "resultados", fra: "résultats", ita: "risultati", jpn: "件", kor: "결과", pol: "wyników", ptb: "resultados", rus: "результатов", spa: "resultados", tha: "ผลลัพธ์", tur: "sonuç", zhs: "结果" },

  // Detail page sections
  "Merchant Price":  { eng: "Merchant Price", deu: "Händlerpreis", esp: "Precio del mercader", fra: "Prix du marchand", ita: "Prezzo del mercante", jpn: "商人の価格", kor: "상인 가격", pol: "Cena kupca", ptb: "Preço do mercador", rus: "Цена торговца", spa: "Precio del mercader", tha: "ราคาพ่อค้า", tur: "Tüccar Fiyatı", zhs: "商人价格" },
  "Powers Applied":  { eng: "Powers Applied", deu: "Angewandte Kräfte", esp: "Poderes aplicados", fra: "Pouvoirs appliqués", ita: "Poteri applicati", jpn: "適用パワー", kor: "적용 파워", pol: "Zastosowane moce", ptb: "Poderes aplicados", rus: "Применяемые силы", spa: "Poderes aplicados", tha: "พลังที่ใช้", tur: "Uygulanan Güçler", zhs: "应用能力" },
  "Related Cards":   { eng: "Related Cards", deu: "Verwandte Karten", esp: "Cartas relacionadas", fra: "Cartes liées", ita: "Carte correlate", jpn: "関連カード", kor: "관련 카드", pol: "Powiązane karty", ptb: "Cartas relacionadas", rus: "Связанные карты", spa: "Cartas relacionadas", tha: "การ์ดที่เกี่ยวข้อง", tur: "İlgili Kartlar", zhs: "相关卡牌" },
  "Other languages": { eng: "Other languages", deu: "Andere Sprachen", esp: "Otros idiomas", fra: "Autres langues", ita: "Altre lingue", jpn: "他の言語", kor: "다른 언어", pol: "Inne języki", ptb: "Outros idiomas", rus: "Другие языки", spa: "Otros idiomas", tha: "ภาษาอื่น", tur: "Diğer Diller", zhs: "其他语言" },
  "Version History": { eng: "Version History", deu: "Versionsgeschichte", esp: "Historial de versiones", fra: "Historique des versions", ita: "Cronologia versioni", jpn: "バージョン履歴", kor: "버전 기록", pol: "Historia wersji", ptb: "Histórico de versões", rus: "История версий", spa: "Historial de versiones", tha: "ประวัติเวอร์ชัน", tur: "Sürüm Geçmişi", zhs: "版本历史" },
  "Gold":            { eng: "Gold", deu: "Gold", esp: "Oro", fra: "Or", ita: "Oro", jpn: "ゴールド", kor: "골드", pol: "Złoto", ptb: "Ouro", rus: "Золото", spa: "Oro", tha: "ทอง", tur: "Altın", zhs: "金币" },
  "Cards":           { eng: "Cards", deu: "Karten", esp: "Cartas", fra: "Cartes", ita: "Carte", jpn: "カード", kor: "카드", pol: "Karty", ptb: "Cartas", rus: "Карты", spa: "Cartas", tha: "การ์ด", tur: "Kartlar", zhs: "卡牌" },
  "Relics":          { eng: "Relics", deu: "Relikte", esp: "Reliquias", fra: "Reliques", ita: "Reliquie", jpn: "レリック", kor: "유물", pol: "Relikty", ptb: "Relíquias", rus: "Реликвии", spa: "Reliquias", tha: "เรลิก", tur: "Kalıntılar", zhs: "遗物" },
  "Potions":         { eng: "Potions", deu: "Tränke", esp: "Pociones", fra: "Potions", ita: "Pozioni", jpn: "ポーション", kor: "물약", pol: "Mikstury", ptb: "Poções", rus: "Зелья", spa: "Pociones", tha: "ยา", tur: "İksirler", zhs: "药水" },
  "Monsters":        { eng: "Monsters", deu: "Monster", esp: "Monstruos", fra: "Monstres", ita: "Mostri", jpn: "モンスター", kor: "몬스터", pol: "Potwory", ptb: "Monstros", rus: "Монстры", spa: "Monstruos", tha: "มอนสเตอร์", tur: "Canavarlar", zhs: "怪物" },
  "Powers":          { eng: "Powers", deu: "Kräfte", esp: "Poderes", fra: "Pouvoirs", ita: "Poteri", jpn: "パワー", kor: "파워", pol: "Moce", ptb: "Poderes", rus: "Силы", spa: "Poderes", tha: "พลัง", tur: "Güçler", zhs: "能力" },
  "Events":          { eng: "Events", deu: "Ereignisse", esp: "Eventos", fra: "Événements", ita: "Eventi", jpn: "イベント", kor: "이벤트", pol: "Wydarzenia", ptb: "Eventos", rus: "События", spa: "Eventos", tha: "อีเวนต์", tur: "Etkinlikler", zhs: "事件" },
  "Characters":      { eng: "Characters", deu: "Charaktere", esp: "Personajes", fra: "Personnages", ita: "Personaggi", jpn: "キャラクター", kor: "캐릭터", pol: "Postacie", ptb: "Personagens", rus: "Персонажи", spa: "Personajes", tha: "ตัวละคร", tur: "Karakterler", zhs: "角色" },
  "Encounters":      { eng: "Encounters", deu: "Begegnungen", esp: "Encuentros", fra: "Rencontres", ita: "Incontri", jpn: "エンカウンター", kor: "조우", pol: "Spotkania", ptb: "Encontros", rus: "Встречи", spa: "Encuentros", tha: "การเผชิญหน้า", tur: "Karşılaşmalar", zhs: "遭遇" },
  "Enchantments":    { eng: "Enchantments", deu: "Verzauberungen", esp: "Encantamientos", fra: "Enchantements", ita: "Incantesimi", jpn: "エンチャント", kor: "인챈트", pol: "Zaklęcia", ptb: "Encantamentos", rus: "Зачарования", spa: "Encantamientos", tha: "มนตร์", tur: "Büyüler", zhs: "附魔" },

  // Sort
  "Compendium":      { eng: "Compendium", deu: "Kompendium", esp: "Compendio", fra: "Compendium", ita: "Compendio", jpn: "図鑑順", kor: "도감", pol: "Kompendium", ptb: "Compêndio", rus: "Компендиум", spa: "Compendio", tha: "สารานุกรม", tur: "Ansiklopedi", zhs: "图鉴" },

  // Nav groups
  "Database":        { eng: "Database", deu: "Datenbank", esp: "Base de datos", fra: "Base de données", ita: "Database", jpn: "データベース", kor: "데이터베이스", pol: "Baza danych", ptb: "Banco de dados", rus: "База данных", spa: "Base de datos", tha: "ฐานข้อมูล", tur: "Veritabanı", zhs: "数据库" },
  "Game Info":       { eng: "Game Info", deu: "Spielinfo", esp: "Info del juego", fra: "Info du jeu", ita: "Info gioco", jpn: "ゲーム情報", kor: "게임 정보", pol: "Info o grze", ptb: "Info do jogo", rus: "Инфо об игре", spa: "Info del juego", tha: "ข้อมูลเกม", tur: "Oyun Bilgisi", zhs: "游戏信息" },
  "About the Site":  { eng: "About the Site", deu: "Über die Seite", esp: "Sobre el sitio", fra: "À propos du site", ita: "Info sul sito", jpn: "サイトについて", kor: "사이트 정보", pol: "O stronie", ptb: "Sobre o site", rus: "О сайте", spa: "Sobre el sitio", tha: "เกี่ยวกับเว็บ", tur: "Site Hakkında", zhs: "关于本站" },

  // Nav link labels
  "Card Library":    { eng: "Card Library", deu: "Kartenbibliothek", esp: "Biblioteca de cartas", fra: "Bibliothèque de cartes", ita: "Libreria carte", jpn: "カードライブラリ", kor: "카드 도서관", pol: "Biblioteka kart", ptb: "Biblioteca de cartas", rus: "Библиотека карт", spa: "Biblioteca de cartas", tha: "คลังการ์ด", tur: "Kart Kütüphanesi", zhs: "卡牌库" },
  "Relic Collection": { eng: "Relic Collection", deu: "Reliktsammlung", esp: "Colección de reliquias", fra: "Collection de reliques", ita: "Collezione reliquie", jpn: "レリックコレクション", kor: "유물 컬렉션", pol: "Kolekcja reliktów", ptb: "Coleção de relíquias", rus: "Коллекция реликвий", spa: "Colección de reliquias", tha: "คอลเลกชันเรลิก", tur: "Kalıntı Koleksiyonu", zhs: "遗物收藏" },
  "Bestiary":        { eng: "Bestiary", deu: "Bestiarium", esp: "Bestiario", fra: "Bestiaire", ita: "Bestiario", jpn: "図鑑", kor: "도감", pol: "Bestiariusz", ptb: "Bestiário", rus: "Бестиарий", spa: "Bestiario", tha: "สัตว์ประหลาด", tur: "Yaratık Ansiklopedisi", zhs: "怪物图鉴" },
  "Potion Lab":      { eng: "Potion Lab", deu: "Trankküche", esp: "Laboratorio de pociones", fra: "Laboratoire de potions", ita: "Laboratorio pozioni", jpn: "ポーション工房", kor: "물약 연구소", pol: "Laboratorium mikstur", ptb: "Laboratório de poções", rus: "Лаборатория зелий", spa: "Laboratorio de pociones", tha: "ห้องปฏิบัติการยา", tur: "İksir Laboratuvarı", zhs: "药水实验室" },
  "Merchant":        { eng: "Merchant", deu: "Händler", esp: "Mercader", fra: "Marchand", ita: "Mercante", jpn: "商人", kor: "상인", pol: "Kupiec", ptb: "Mercador", rus: "Торговец", spa: "Mercader", tha: "พ่อค้า", tur: "Tüccar", zhs: "商人" },
  "Keywords":        { eng: "Keywords", deu: "Schlüsselwörter", esp: "Palabras clave", fra: "Mots-clés", ita: "Parole chiave", jpn: "キーワード", kor: "키워드", pol: "Słowa kluczowe", ptb: "Palavras-chave", rus: "Ключевые слова", spa: "Palabras clave", tha: "คีย์เวิร์ด", tur: "Anahtar Kelimeler", zhs: "关键词" },
  "Compare":         { eng: "Compare", deu: "Vergleichen", esp: "Comparar", fra: "Comparer", ita: "Confronta", jpn: "比較", kor: "비교", pol: "Porównaj", ptb: "Comparar", rus: "Сравнить", spa: "Comparar", tha: "เปรียบเทียบ", tur: "Karşılaştır", zhs: "比较" },
  "Timeline":        { eng: "Timeline", deu: "Zeitleiste", esp: "Línea de tiempo", fra: "Chronologie", ita: "Cronologia", jpn: "タイムライン", kor: "타임라인", pol: "Oś czasu", ptb: "Linha do tempo", rus: "Хронология", spa: "Línea de tiempo", tha: "ไทม์ไลน์", tur: "Zaman Çizelgesi", zhs: "时间线" },
  "Images":          { eng: "Images", deu: "Bilder", esp: "Imágenes", fra: "Images", ita: "Immagini", jpn: "画像", kor: "이미지", pol: "Obrazy", ptb: "Imagens", rus: "Изображения", spa: "Imágenes", tha: "รูปภาพ", tur: "Görseller", zhs: "图片" },
  "Reference":       { eng: "Reference", deu: "Referenz", esp: "Referencia", fra: "Référence", ita: "Riferimento", jpn: "リファレンス", kor: "레퍼런스", pol: "Referencja", ptb: "Referência", rus: "Справочник", spa: "Referencia", tha: "อ้างอิง", tur: "Referans", zhs: "参考" },
  "Showcase":        { eng: "Showcase", deu: "Galerie", esp: "Galería", fra: "Vitrine", ita: "Vetrina", jpn: "ショーケース", kor: "쇼케이스", pol: "Prezentacja", ptb: "Vitrine", rus: "Витрина", spa: "Galería", tha: "โชว์เคส", tur: "Vitrin", zhs: "展示" },
  "Changelog":       { eng: "Changelog", deu: "Änderungsprotokoll", esp: "Registro de cambios", fra: "Journal des modifications", ita: "Registro modifiche", jpn: "変更履歴", kor: "변경 이력", pol: "Dziennik zmian", ptb: "Registro de alterações", rus: "Журнал изменений", spa: "Registro de cambios", tha: "บันทึกการเปลี่ยนแปลง", tur: "Değişiklik Günlüğü", zhs: "更新日志" },
  "About":           { eng: "About", deu: "Über", esp: "Acerca de", fra: "À propos", ita: "Info", jpn: "概要", kor: "소개", pol: "O nas", ptb: "Sobre", rus: "О проекте", spa: "Acerca de", tha: "เกี่ยวกับ", tur: "Hakkında", zhs: "关于" },
  "Developers":      { eng: "Developers", deu: "Entwickler", esp: "Desarrolladores", fra: "Développeurs", ita: "Sviluppatori", jpn: "開発者", kor: "개발자", pol: "Deweloperzy", ptb: "Desenvolvedores", rus: "Разработчики", spa: "Desarrolladores", tha: "นักพัฒนา", tur: "Geliştiriciler", zhs: "开发者" },
  "Discord":         { eng: "Discord", deu: "Discord", esp: "Discord", fra: "Discord", ita: "Discord", jpn: "Discord", kor: "Discord", pol: "Discord", ptb: "Discord", rus: "Discord", spa: "Discord", tha: "Discord", tur: "Discord", zhs: "Discord" },

  // Misc
  "Share":           { eng: "Share", deu: "Teilen", esp: "Compartir", fra: "Partager", ita: "Condividi", jpn: "共有", kor: "공유", pol: "Udostępnij", ptb: "Compartilhar", rus: "Поделиться", spa: "Compartir", tha: "แชร์", tur: "Paylaş", zhs: "分享" },
  "Loading...":      { eng: "Loading...", deu: "Laden...", esp: "Cargando...", fra: "Chargement...", ita: "Caricamento...", jpn: "読み込み中...", kor: "로딩...", pol: "Ładowanie...", ptb: "Carregando...", rus: "Загрузка...", spa: "Cargando...", tha: "กำลังโหลด...", tur: "Yükleniyor...", zhs: "加载中..." },
  "Not Found":       { eng: "Not Found", deu: "Nicht gefunden", esp: "No encontrado", fra: "Non trouvé", ita: "Non trovato", jpn: "見つかりません", kor: "찾을 수 없음", pol: "Nie znaleziono", ptb: "Não encontrado", rus: "Не найдено", spa: "No encontrado", tha: "ไม่พบ", tur: "Bulunamadı", zhs: "未找到" },
  "Damage Values":   { eng: "Damage Values", deu: "Schadenswerte", esp: "Valores de daño", fra: "Valeurs de dégâts", ita: "Valori di danno", jpn: "ダメージ値", kor: "데미지 수치", pol: "Wartości obrażeń", ptb: "Valores de dano", rus: "Значения урона", spa: "Valores de daño", tha: "ค่าความเสียหาย", tur: "Hasar Değerleri", zhs: "伤害值" },
  "Block Values":    { eng: "Block Values", deu: "Blockwerte", esp: "Valores de bloqueo", fra: "Valeurs de blocage", ita: "Valori di blocco", jpn: "ブロック値", kor: "방어 수치", pol: "Wartości bloku", ptb: "Valores de bloqueio", rus: "Значения блока", spa: "Valores de bloqueo", tha: "ค่าป้องกัน", tur: "Blok Değerleri", zhs: "格挡值" },
  "Moves":           { eng: "Moves", deu: "Züge", esp: "Movimientos", fra: "Coups", ita: "Mosse", jpn: "ムーブ", kor: "행동", pol: "Ruchy", ptb: "Movimentos", rus: "Ходы", spa: "Movimientos", tha: "การเคลื่อนไหว", tur: "Hamleler", zhs: "招式" },

  // Page taglines / descriptions
  "cards_tagline": { eng: "Browse every card across Ironclad, Silent, Defect, Necrobinder, and Regent. Filter by character, type, rarity, and keywords.", deu: "Alle Karten durchsuchen — Ironclad, Silent, Defect, Necrobinder und Regent. Filtern nach Charakter, Typ, Seltenheit und Schlüsselwörtern.", esp: "Explora todas las cartas de Ironclad, Silent, Defect, Necrobinder y Regent. Filtra por personaje, tipo, rareza y palabras clave.", fra: "Parcourez toutes les cartes d'Ironclad, Silent, Defect, Necrobinder et Regent. Filtrez par personnage, type, rareté et mots-clés.", ita: "Sfoglia tutte le carte di Ironclad, Silent, Defect, Necrobinder e Regent. Filtra per personaggio, tipo, rarità e parole chiave.", jpn: "アイアンクラッド、サイレント、ディフェクト、ネクロバインダー、リージェントの全カードを閲覧。キャラクター、タイプ、レアリティ、キーワードでフィルター。", kor: "아이언클래드, 사일런트, 디펙트, 네크로바인더, 리전트의 모든 카드를 탐색하세요. 캐릭터, 유형, 희귀도, 키워드로 필터링.", pol: "Przeglądaj wszystkie karty Ironclada, Silent, Defecta, Necrobindera i Regenta. Filtruj według postaci, typu, rzadkości i słów kluczowych.", ptb: "Navegue por todas as cartas de Ironclad, Silent, Defect, Necrobinder e Regent. Filtre por personagem, tipo, raridade e palavras-chave.", rus: "Просмотрите все карты Ironclad, Silent, Defect, Necrobinder и Regent. Фильтруйте по персонажу, типу, редкости и ключевым словам.", spa: "Explora todas las cartas de Ironclad, Silent, Defect, Necrobinder y Regent. Filtra por personaje, tipo, rareza y palabras clave.", tha: "เรียกดูการ์ดทั้งหมดของ Ironclad, Silent, Defect, Necrobinder และ Regent กรองตามตัวละคร ประเภท ความหายาก และคีย์เวิร์ด", tur: "Ironclad, Silent, Defect, Necrobinder ve Regent'ın tüm kartlarını inceleyin. Karakter, tür, nadirlik ve anahtar kelimelere göre filtreleyin.", zhs: "浏览铁甲战士、沉默猎手、缺陷体、亡灵师、摄政王的所有卡牌。按角色、类型、稀有度和关键词筛选。" },
  "relics_tagline": { eng: "Browse every relic across all rarities and character pools. Filter by rarity and pool.", deu: "Alle Relikte aller Seltenheiten und Charakterpools durchsuchen. Nach Seltenheit und Pool filtern.", esp: "Explora todas las reliquias de todas las rarezas y grupos de personajes. Filtra por rareza y grupo.", fra: "Parcourez toutes les reliques de toutes les raretés et groupes de personnages. Filtrez par rareté et groupe.", ita: "Sfoglia tutte le reliquie di ogni rarità e gruppo di personaggi. Filtra per rarità e gruppo.", jpn: "全レアリティ・全キャラクタープールのレリックを閲覧。レアリティとプールでフィルター。", kor: "모든 희귀도와 캐릭터 풀의 유물을 탐색하세요. 희귀도와 풀로 필터링.", pol: "Przeglądaj wszystkie relikty wszystkich rzadkości i pul postaci. Filtruj według rzadkości i puli.", ptb: "Navegue por todas as relíquias de todas as raridades e grupos de personagens. Filtre por raridade e grupo.", rus: "Просмотрите все реликвии всех редкостей и пулов персонажей. Фильтруйте по редкости и пулу.", spa: "Explora todas las reliquias de todas las rarezas y grupos de personajes. Filtra por rareza y grupo.", tha: "เรียกดูเรลิกทั้งหมดทุกความหายากและกลุ่มตัวละคร กรองตามความหายากและกลุ่ม", tur: "Tüm nadirlik ve karakter havuzlarındaki kalıntıları inceleyin. Nadirlik ve havuza göre filtreleyin.", zhs: "浏览所有稀有度和角色池的遗物。按稀有度和池筛选。" },
  "potions_tagline": { eng: "Browse every potion. Filter by rarity and character pool.", deu: "Alle Tränke durchsuchen. Nach Seltenheit und Charakterpool filtern.", esp: "Explora todas las pociones. Filtra por rareza y grupo de personajes.", fra: "Parcourez toutes les potions. Filtrez par rareté et groupe de personnages.", ita: "Sfoglia tutte le pozioni. Filtra per rarità e gruppo di personaggi.", jpn: "全ポーションを閲覧。レアリティとキャラクタープールでフィルター。", kor: "모든 물약을 탐색하세요. 희귀도와 캐릭터 풀로 필터링.", pol: "Przeglądaj wszystkie mikstury. Filtruj według rzadkości i puli postaci.", ptb: "Navegue por todas as poções. Filtre por raridade e grupo de personagens.", rus: "Просмотрите все зелья. Фильтруйте по редкости и пулу персонажей.", spa: "Explora todas las pociones. Filtra por rareza y grupo de personajes.", tha: "เรียกดูยาทั้งหมด กรองตามความหายากและกลุ่มตัวละคร", tur: "Tüm iksirleri inceleyin. Nadirlik ve karakter havuzuna göre filtreleyin.", zhs: "浏览所有药水。按稀有度和角色池筛选。" },
  "monsters_tagline": { eng: "Browse every monster — normals, elites, and bosses. View HP values, moves, damage stats, and ascension scaling.", deu: "Alle Monster durchsuchen — Normale, Eliten und Bosse. HP-Werte, Züge, Schadenswerte und Aufstiegsskalierung ansehen.", esp: "Explora todos los monstruos — normales, élites y jefes. Consulta HP, movimientos, daño y escalado de ascensión.", fra: "Parcourez tous les monstres — normaux, élites et boss. Consultez les PV, coups, dégâts et la progression d'ascension.", ita: "Sfoglia tutti i mostri — normali, élite e boss. Visualizza HP, mosse, danni e scalatura ascensione.", jpn: "全モンスターを閲覧 — ノーマル、エリート、ボス。HP、ムーブ、ダメージ、アセンション補正を確認。", kor: "모든 몬스터 탐색 — 일반, 엘리트, 보스. HP, 행동, 데미지, 승천 스케일링 확인.", pol: "Przeglądaj wszystkie potwory — zwykłe, elitarne i bossów. Sprawdź HP, ruchy, obrażenia i skalowanie ascensji.", ptb: "Navegue por todos os monstros — normais, elites e chefes. Veja HP, movimentos, dano e escalonamento de ascensão.", rus: "Просмотрите всех монстров — обычных, элитных и боссов. HP, ходы, урон и масштабирование восхождения.", spa: "Explora todos los monstruos — normales, élites y jefes. Consulta HP, movimientos, daño y escalado de ascensión.", tha: "เรียกดูมอนสเตอร์ทั้งหมด — ปกติ อีลิท และบอส ดู HP การเคลื่อนไหว ค่าความเสียหาย และ Ascension", tur: "Tüm canavarları inceleyin — normal, elit ve boss. HP, hamleler, hasar ve tırmanma ölçeklendirmesini görüntüleyin.", zhs: "浏览所有怪物 — 普通、精英和Boss。查看HP、招式、伤害和登塔缩放。" },
  "powers_tagline": { eng: "Browse every power — buffs, debuffs, and neutral effects. Filter by type and stack behavior.", deu: "Alle Kräfte durchsuchen — Buffs, Debuffs und neutrale Effekte. Nach Typ und Stapelverhalten filtern.", esp: "Explora todos los poderes — mejoras, debilitaciones y efectos neutrales. Filtra por tipo y comportamiento de acumulación.", fra: "Parcourez tous les pouvoirs — améliorations, affaiblissements et effets neutres. Filtrez par type et comportement d'empilement.", ita: "Sfoglia tutti i poteri — buff, debuff ed effetti neutrali. Filtra per tipo e comportamento di accumulo.", jpn: "全パワーを閲覧 — バフ、デバフ、中立効果。タイプとスタック動作でフィルター。", kor: "모든 파워 탐색 — 버프, 디버프, 중립 효과. 유형과 스택 동작으로 필터링.", pol: "Przeglądaj wszystkie moce — buffy, debuffy i efekty neutralne. Filtruj według typu i zachowania stosu.", ptb: "Navegue por todos os poderes — buffs, debuffs e efeitos neutros. Filtre por tipo e comportamento de acúmulo.", rus: "Просмотрите все силы — баффы, дебаффы и нейтральные эффекты. Фильтруйте по типу и поведению стака.", spa: "Explora todos los poderes — mejoras, debilitaciones y efectos neutrales. Filtra por tipo y acumulación.", tha: "เรียกดูพลังทั้งหมด — บัฟ ดีบัฟ และเอฟเฟกต์กลาง กรองตามประเภทและพฤติกรรมสแต็ก", tur: "Tüm güçleri inceleyin — buff, debuff ve nötr etkiler. Tür ve yığılma davranışına göre filtreleyin.", zhs: "浏览所有能力 — 增益、减益和中性效果。按类型和叠加行为筛选。" },
  "events_tagline": { eng: "Browse every event including shrine events, Ancient encounters, and story events. View choices, dialogue, and outcomes.", deu: "Alle Ereignisse durchsuchen — Schrein-Ereignisse, Uralte Begegnungen und Story-Ereignisse. Entscheidungen, Dialoge und Ergebnisse ansehen.", esp: "Explora todos los eventos incluidos santuarios, encuentros ancestrales y eventos de historia. Consulta decisiones, diálogos y resultados.", fra: "Parcourez tous les événements — sanctuaires, rencontres ancestrales et événements d'histoire. Consultez les choix, dialogues et résultats.", ita: "Sfoglia tutti gli eventi — santuari, incontri ancestrali ed eventi della storia. Visualizza scelte, dialoghi e risultati.", jpn: "全イベントを閲覧 — 祠イベント、エンシェント遭遇、ストーリーイベント。選択肢、対話、結果を確認。", kor: "모든 이벤트 탐색 — 제단 이벤트, 고대 조우, 스토리 이벤트. 선택지, 대화, 결과 확인.", pol: "Przeglądaj wszystkie wydarzenia — sanktuaria, pradawne spotkania i wydarzenia fabularne. Sprawdź wybory, dialogi i wyniki.", ptb: "Navegue por todos os eventos — santuários, encontros ancestrais e eventos de história. Veja escolhas, diálogos e resultados.", rus: "Просмотрите все события — святилища, встречи с Древними и сюжетные события. Выборы, диалоги и исходы.", spa: "Explora todos los eventos — santuarios, encuentros ancestrales y eventos de historia. Consulta decisiones, diálogos y resultados.", tha: "เรียกดูอีเวนต์ทั้งหมด — ศาลเจ้า การเผชิญหน้าโบราณ และอีเวนต์เรื่องราว ดูทางเลือก บทสนทนา และผลลัพธ์", tur: "Tüm etkinlikleri inceleyin — tapınak, Kadim karşılaşmalar ve hikaye etkinlikleri. Seçenekleri, diyalogları ve sonuçları görüntüleyin.", zhs: "浏览所有事件 — 神龛事件、远古遭遇和故事事件。查看选择、对话和结果。" },
  "characters_tagline": { eng: "All playable characters — view starting decks, relics, HP, gold, energy, and more.", deu: "Alle spielbaren Charaktere — Startdecks, Relikte, HP, Gold, Energie und mehr.", esp: "Todos los personajes jugables — mazos iniciales, reliquias, HP, oro, energía y más.", fra: "Tous les personnages jouables — decks de départ, reliques, PV, or, énergie et plus.", ita: "Tutti i personaggi giocabili — deck iniziali, reliquie, HP, oro, energia e altro.", jpn: "全プレイアブルキャラクター — 初期デッキ、レリック、HP、ゴールド、エネルギーなど。", kor: "모든 플레이어블 캐릭터 — 시작 덱, 유물, HP, 골드, 에너지 등.", pol: "Wszystkie grywalne postacie — startowe talie, relikty, HP, złoto, energia i więcej.", ptb: "Todos os personagens jogáveis — decks iniciais, relíquias, HP, ouro, energia e mais.", rus: "Все игровые персонажи — стартовые колоды, реликвии, HP, золото, энергия и другое.", spa: "Todos los personajes jugables — mazos iniciales, reliquias, HP, oro, energía y más.", tha: "ตัวละครที่เล่นได้ทั้งหมด — เด็คเริ่มต้น เรลิก HP ทอง พลังงาน และอื่นๆ", tur: "Tüm oynanabilir karakterler — başlangıç desteleri, kalıntılar, HP, altın, enerji ve daha fazlası.", zhs: "所有可玩角色 — 初始牌组、遗物、HP、金币、能量等。" },
  "encounters_tagline": { eng: "Browse every combat encounter. Filter by room type and act.", deu: "Alle Kampfbegegnungen durchsuchen. Nach Raumtyp und Akt filtern.", esp: "Explora todos los encuentros de combate. Filtra por tipo de sala y acto.", fra: "Parcourez toutes les rencontres de combat. Filtrez par type de salle et acte.", ita: "Sfoglia tutti gli scontri di combattimento. Filtra per tipo di stanza e atto.", jpn: "全戦闘エンカウンターを閲覧。部屋タイプとアクトでフィルター。", kor: "모든 전투 조우를 탐색하세요. 방 유형과 막으로 필터링.", pol: "Przeglądaj wszystkie spotkania bojowe. Filtruj według typu pokoju i aktu.", ptb: "Navegue por todos os encontros de combate. Filtre por tipo de sala e ato.", rus: "Просмотрите все боевые встречи. Фильтруйте по типу комнаты и акту.", spa: "Explora todos los encuentros de combate. Filtra por tipo de sala y acto.", tha: "เรียกดูการเผชิญหน้าการต่อสู้ทั้งหมด กรองตามประเภทห้องและฉาก", tur: "Tüm savaş karşılaşmalarını inceleyin. Oda türü ve perdeye göre filtreleyin.", zhs: "浏览所有战斗遭遇。按房间类型和幕筛选。" },
  "enchantments_tagline": { eng: "Browse every enchantment. Filter by card type and view effects, stackability, and extra card text.", deu: "Alle Verzauberungen durchsuchen. Nach Kartentyp filtern und Effekte, Stapelbarkeit und zusätzlichen Kartentext ansehen.", esp: "Explora todos los encantamientos. Filtra por tipo de carta y consulta efectos, acumulabilidad y texto adicional.", fra: "Parcourez tous les enchantements. Filtrez par type de carte et consultez les effets, l'empilabilité et le texte supplémentaire.", ita: "Sfoglia tutti gli incantesimi. Filtra per tipo di carta e visualizza effetti, accumulabilità e testo aggiuntivo.", jpn: "全エンチャントを閲覧。カードタイプでフィルターし、効果、重複可否、追加テキストを確認。", kor: "모든 인챈트를 탐색하세요. 카드 유형으로 필터링하고 효과, 중첩 가능 여부, 추가 텍스트를 확인.", pol: "Przeglądaj wszystkie zaklęcia. Filtruj według typu karty i sprawdź efekty, możliwość stosowania i dodatkowy tekst.", ptb: "Navegue por todos os encantamentos. Filtre por tipo de carta e veja efeitos, acumulabilidade e texto adicional.", rus: "Просмотрите все зачарования. Фильтруйте по типу карты и просматривайте эффекты, складываемость и доп. текст.", spa: "Explora todos los encantamientos. Filtra por tipo de carta y consulta efectos, acumulabilidad y texto adicional.", tha: "เรียกดูมนตร์ทั้งหมด กรองตามประเภทการ์ดและดูเอฟเฟกต์ การซ้อน และข้อความเพิ่มเติม", tur: "Tüm büyüleri inceleyin. Kart türüne göre filtreleyin ve etkileri, yığılabilirliği ve ek kart metnini görüntüleyin.", zhs: "浏览所有附魔。按卡牌类型筛选，查看效果、可叠加性和额外文本。" },

  // About the Site page taglines
  "about_tagline": { eng: "About Spire Codex — a community-built database for Slay the Spire 2. Learn about the data pipeline, tech stack, and how the site works.", deu: "Über Spire Codex — eine Community-Datenbank für Slay the Spire 2. Erfahre mehr über die Datenpipeline, den Tech-Stack und wie die Seite funktioniert.", esp: "Sobre Spire Codex — una base de datos comunitaria para Slay the Spire 2. Conoce la pipeline de datos, el stack tecnológico y cómo funciona el sitio.", fra: "À propos de Spire Codex — une base de données communautaire pour Slay the Spire 2. Découvrez le pipeline de données, la stack technique et le fonctionnement du site.", ita: "Informazioni su Spire Codex — un database comunitario per Slay the Spire 2. Scopri la pipeline dati, lo stack tecnologico e come funziona il sito.", jpn: "Spire Codexについて — Slay the Spire 2のコミュニティデータベース。データパイプライン、技術スタック、サイトの仕組みについて。", kor: "Spire Codex 소개 — Slay the Spire 2 커뮤니티 데이터베이스. 데이터 파이프라인, 기술 스택, 사이트 작동 방식을 알아보세요.", pol: "O Spire Codex — społecznościowa baza danych dla Slay the Spire 2. Dowiedz się o pipeline danych, stosie technologicznym i jak działa strona.", ptb: "Sobre o Spire Codex — um banco de dados comunitário para Slay the Spire 2. Saiba mais sobre o pipeline de dados, stack tecnológico e como o site funciona.", rus: "О Spire Codex — общественная база данных для Slay the Spire 2. Узнайте о конвейере данных, технологиях и работе сайта.", spa: "Sobre Spire Codex — una base de datos comunitaria para Slay the Spire 2. Conoce la pipeline de datos, el stack tecnológico y cómo funciona el sitio.", tha: "เกี่ยวกับ Spire Codex — ฐานข้อมูลจากชุมชนสำหรับ Slay the Spire 2 เรียนรู้เกี่ยวกับ pipeline ข้อมูล tech stack และการทำงานของเว็บ", tur: "Spire Codex Hakkında — Slay the Spire 2 için topluluk tarafından oluşturulmuş bir veritabanı. Veri hattı, teknoloji yığını ve sitenin nasıl çalıştığını öğrenin.", zhs: "关于 Spire Codex — 一个社区构建的杀戮尖塔2数据库。了解数据管道、技术栈和网站运作方式。" },
  "changelog_tagline": { eng: "Track what changes between game updates — new cards, balance tweaks, removed content, and more.", deu: "Verfolge Änderungen zwischen Spielupdates — neue Karten, Balance-Anpassungen, entfernte Inhalte und mehr.", esp: "Sigue los cambios entre actualizaciones — nuevas cartas, ajustes de equilibrio, contenido eliminado y más.", fra: "Suivez les changements entre les mises à jour — nouvelles cartes, équilibrages, contenu supprimé et plus.", ita: "Segui le modifiche tra gli aggiornamenti — nuove carte, bilanciamenti, contenuti rimossi e altro.", jpn: "ゲームアップデート間の変更を追跡 — 新カード、バランス調整、削除コンテンツなど。", kor: "게임 업데이트 간 변경 사항을 추적하세요 — 새 카드, 밸런스 조정, 삭제된 콘텐츠 등.", pol: "Śledź zmiany między aktualizacjami gry — nowe karty, poprawki balansu, usunięte treści i więcej.", ptb: "Acompanhe as mudanças entre atualizações — novas cartas, ajustes de balanceamento, conteúdo removido e mais.", rus: "Отслеживайте изменения между обновлениями — новые карты, правки баланса, удалённый контент и другое.", spa: "Sigue los cambios entre actualizaciones — nuevas cartas, ajustes de equilibrio, contenido eliminado y más.", tha: "ติดตามการเปลี่ยนแปลงระหว่างอัปเดตเกม — การ์ดใหม่ การปรับสมดุล เนื้อหาที่ถูกลบ และอื่นๆ", tur: "Oyun güncellemeleri arasındaki değişiklikleri takip edin — yeni kartlar, denge ayarları, kaldırılan içerik ve daha fazlası.", zhs: "追踪游戏更新之间的变化 — 新卡牌、平衡调整、删除内容等。" },
  "showcase_tagline": { eng: "Community projects built with the Spire Codex API. Want to add yours? Submit a PR on GitHub.", deu: "Community-Projekte mit der Spire Codex API. Eigenes Projekt hinzufügen? Sende einen PR auf GitHub.", esp: "Proyectos de la comunidad creados con la API de Spire Codex. ¿Quieres añadir el tuyo? Envía un PR en GitHub.", fra: "Projets communautaires utilisant l'API Spire Codex. Vous voulez ajouter le vôtre ? Soumettez un PR sur GitHub.", ita: "Progetti della community realizzati con l'API Spire Codex. Vuoi aggiungere il tuo? Invia una PR su GitHub.", jpn: "Spire Codex APIを使ったコミュニティプロジェクト。あなたのプロジェクトを追加したい場合はGitHubでPRを送信してください。", kor: "Spire Codex API로 만든 커뮤니티 프로젝트. 추가하고 싶으신가요? GitHub에서 PR을 제출하세요.", pol: "Projekty społeczności zbudowane z API Spire Codex. Chcesz dodać swój? Wyślij PR na GitHubie.", ptb: "Projetos da comunidade feitos com a API do Spire Codex. Quer adicionar o seu? Envie um PR no GitHub.", rus: "Проекты сообщества на API Spire Codex. Хотите добавить свой? Отправьте PR на GitHub.", spa: "Proyectos de la comunidad creados con la API de Spire Codex. ¿Quieres añadir el tuyo? Envía un PR en GitHub.", tha: "โปรเจกต์ชุมชนที่สร้างด้วย Spire Codex API ต้องการเพิ่มของคุณ? ส่ง PR บน GitHub", tur: "Spire Codex API ile oluşturulmuş topluluk projeleri. Kendinizinkini eklemek ister misiniz? GitHub'da bir PR gönderin.", zhs: "使用 Spire Codex API 构建的社区项目。想添加你的项目？在 GitHub 上提交 PR。" },
  "developers_tagline": { eng: "Build tools, bots, and content with Spire Codex data. Everything is free and open.", deu: "Erstelle Tools, Bots und Inhalte mit Spire Codex-Daten. Alles ist kostenlos und offen.", esp: "Crea herramientas, bots y contenido con los datos de Spire Codex. Todo es gratuito y abierto.", fra: "Créez des outils, bots et contenus avec les données Spire Codex. Tout est gratuit et ouvert.", ita: "Crea strumenti, bot e contenuti con i dati di Spire Codex. Tutto è gratuito e aperto.", jpn: "Spire Codexのデータでツール、ボット、コンテンツを作成。すべて無料でオープン。", kor: "Spire Codex 데이터로 도구, 봇, 콘텐츠를 만드세요. 모든 것이 무료이고 오픈됩니다.", pol: "Twórz narzędzia, boty i treści z danymi Spire Codex. Wszystko jest darmowe i otwarte.", ptb: "Crie ferramentas, bots e conteúdo com os dados do Spire Codex. Tudo é gratuito e aberto.", rus: "Создавайте инструменты, ботов и контент с данными Spire Codex. Всё бесплатно и открыто.", spa: "Crea herramientas, bots y contenido con los datos de Spire Codex. Todo es gratuito y abierto.", tha: "สร้างเครื่องมือ บอท และเนื้อหาด้วยข้อมูล Spire Codex ทุกอย่างฟรีและเปิดกว้าง", tur: "Spire Codex verileriyle araçlar, botlar ve içerik oluşturun. Her şey ücretsiz ve açık.", zhs: "使用 Spire Codex 数据构建工具、机器人和内容。一切免费开放。" },
  "merchant_tagline": { eng: "All merchant pricing extracted from the game source code. Prices vary within the listed ranges due to a per-seed random multiplier.", deu: "Alle Händlerpreise aus dem Spielquellcode extrahiert. Preise variieren innerhalb der angegebenen Bereiche durch einen zufälligen Seed-Multiplikator.", esp: "Todos los precios del mercader extraídos del código fuente del juego. Los precios varían dentro de los rangos indicados debido a un multiplicador aleatorio por semilla.", fra: "Tous les prix du marchand extraits du code source du jeu. Les prix varient dans les fourchettes indiquées en raison d'un multiplicateur aléatoire par graine.", ita: "Tutti i prezzi del mercante estratti dal codice sorgente del gioco. I prezzi variano entro i range indicati a causa di un moltiplicatore casuale per seed.", jpn: "すべての商人価格はゲームソースコードから抽出。価格はシードごとのランダム乗数により表示範囲内で変動します。", kor: "모든 상인 가격은 게임 소스 코드에서 추출되었습니다. 가격은 시드별 랜덤 배율로 인해 표시 범위 내에서 변동됩니다.", pol: "Wszystkie ceny kupca wyciągnięte z kodu źródłowego gry. Ceny różnią się w podanych zakresach z powodu losowego mnożnika opartego na seedzie.", ptb: "Todos os preços do mercador extraídos do código-fonte do jogo. Os preços variam dentro das faixas listadas devido a um multiplicador aleatório por seed.", rus: "Все цены торговца извлечены из исходного кода игры. Цены варьируются в указанных диапазонах из-за случайного множителя на основе сида.", spa: "Todos los precios del mercader extraídos del código fuente del juego. Los precios varían dentro de los rangos indicados debido a un multiplicador aleatorio por semilla.", tha: "ราคาพ่อค้าทั้งหมดดึงจากซอร์สโค้ดเกม ราคาจะแตกต่างกันในช่วงที่แสดงเนื่องจากตัวคูณสุ่มต่อ seed", tur: "Tüm tüccar fiyatları oyun kaynak kodundan çıkarılmıştır. Fiyatlar, seed bazlı rastgele çarpan nedeniyle listelenen aralıklarda değişir.", zhs: "所有商人价格从游戏源代码提取。价格因每个种子的随机乘数而在列出的范围内变化。" },
  "compare_tagline": { eng: "Compare characters side by side — stats, card pool breakdowns, keyword distributions, and starting decks.", deu: "Charaktere nebeneinander vergleichen — Werte, Kartenpool-Aufschlüsselungen, Schlüsselwort-Verteilungen und Startdecks.", esp: "Compara personajes lado a lado — estadísticas, desglose de mazo, distribución de palabras clave y mazos iniciales.", fra: "Comparez les personnages côte à côte — statistiques, répartitions des pools de cartes, distributions des mots-clés et decks de départ.", ita: "Confronta i personaggi fianco a fianco — statistiche, composizione pool di carte, distribuzioni parole chiave e deck iniziali.", jpn: "キャラクターを並べて比較 — ステータス、カードプール、キーワード分布、初期デッキ。", kor: "캐릭터를 나란히 비교 — 스탯, 카드 풀 분석, 키워드 분포, 시작 덱.", pol: "Porównaj postacie obok siebie — statystyki, rozkład puli kart, dystrybucja słów kluczowych i startowe talie.", ptb: "Compare personagens lado a lado — atributos, composição do pool de cartas, distribuição de palavras-chave e decks iniciais.", rus: "Сравните персонажей бок о бок — характеристики, состав пулов карт, распределение ключевых слов и стартовые колоды.", spa: "Compara personajes lado a lado — estadísticas, desglose de mazo, distribución de palabras clave y mazos iniciales.", tha: "เปรียบเทียบตัวละครเคียงข้างกัน — สถิติ การแจกแจงพูลการ์ด การกระจายคีย์เวิร์ด และเด็คเริ่มต้น", tur: "Karakterleri yan yana karşılaştırın — istatistikler, kart havuzu dağılımları, anahtar kelime dağılımları ve başlangıç desteleri.", zhs: "并排比较角色 — 属性、卡池分析、关键词分布和初始牌组。" },
  "keywords_tagline": { eng: "Keywords define special behaviors for cards. Click a keyword to see all cards with that keyword.", deu: "Schlüsselwörter definieren besondere Verhaltensweisen für Karten. Klicke auf ein Schlüsselwort, um alle Karten damit zu sehen.", esp: "Las palabras clave definen comportamientos especiales para las cartas. Haz clic en una palabra clave para ver todas las cartas con ella.", fra: "Les mots-clés définissent des comportements spéciaux pour les cartes. Cliquez sur un mot-clé pour voir toutes les cartes associées.", ita: "Le parole chiave definiscono comportamenti speciali per le carte. Clicca su una parola chiave per vedere tutte le carte associate.", jpn: "キーワードはカードの特別な動作を定義します。キーワードをクリックして、そのキーワードを持つ全カードを表示。", kor: "키워드는 카드의 특수 동작을 정의합니다. 키워드를 클릭하여 해당 키워드가 있는 모든 카드를 확인하세요.", pol: "Słowa kluczowe definiują specjalne zachowania kart. Kliknij słowo kluczowe, aby zobaczyć wszystkie karty z nim.", ptb: "Palavras-chave definem comportamentos especiais para cartas. Clique em uma palavra-chave para ver todas as cartas associadas.", rus: "Ключевые слова определяют особое поведение карт. Нажмите на ключевое слово, чтобы увидеть все карты с ним.", spa: "Las palabras clave definen comportamientos especiales para las cartas. Haz clic en una palabra clave para ver todas las cartas con ella.", tha: "คีย์เวิร์ดกำหนดพฤติกรรมพิเศษของการ์ด คลิกคีย์เวิร์ดเพื่อดูการ์ดทั้งหมดที่มีคีย์เวิร์ดนั้น", tur: "Anahtar kelimeler kartlar için özel davranışlar tanımlar. Tüm kartları görmek için bir anahtar kelimeye tıklayın.", zhs: "关键词定义卡牌的特殊行为。点击关键词查看拥有该关键词的所有卡牌。" },
  "The complete database for Slay the Spire 2": { eng: "The complete database for Slay the Spire 2", deu: "Die vollständige Datenbank für Slay the Spire 2", esp: "La base de datos completa para Slay the Spire 2", fra: "La base de données complète pour Slay the Spire 2", ita: "Il database completo per Slay the Spire 2", jpn: "Slay the Spire 2の完全データベース", kor: "Slay the Spire 2 완전 데이터베이스", pol: "Kompletna baza danych Slay the Spire 2", ptb: "O banco de dados completo para Slay the Spire 2", rus: "Полная база данных Slay the Spire 2", spa: "La base de datos completa para Slay the Spire 2", tha: "ฐานข้อมูลที่สมบูรณ์สำหรับ Slay the Spire 2", tur: "Slay the Spire 2 için eksiksiz veritabanı", zhs: "杀戮尖塔2完整数据库" },
  "Merchant Guide": { eng: "Merchant Guide", deu: "Händler-Guide", esp: "Guía del mercader", fra: "Guide du marchand", ita: "Guida al mercante", jpn: "商人ガイド", kor: "상인 가이드", pol: "Przewodnik kupca", ptb: "Guia do mercador", rus: "Гид по торговцу", spa: "Guía del mercader", tha: "คู่มือพ่อค้า", tur: "Tüccar Rehberi", zhs: "商人指南" },
  "Character Comparisons": { eng: "Character Comparisons", deu: "Charaktervergleiche", esp: "Comparaciones de personajes", fra: "Comparaisons de personnages", ita: "Confronti tra personaggi", jpn: "キャラクター比較", kor: "캐릭터 비교", pol: "Porównania postaci", ptb: "Comparações de personagens", rus: "Сравнение персонажей", spa: "Comparaciones de personajes", tha: "เปรียบเทียบตัวละคร", tur: "Karakter Karşılaştırmaları", zhs: "角色对比" },
  "Card Keywords": { eng: "Card Keywords", deu: "Karten-Schlüsselwörter", esp: "Palabras clave de cartas", fra: "Mots-clés des cartes", ita: "Parole chiave delle carte", jpn: "カードキーワード", kor: "카드 키워드", pol: "Słowa kluczowe kart", ptb: "Palavras-chave das cartas", rus: "Ключевые слова карт", spa: "Palabras clave de cartas", tha: "คีย์เวิร์ดการ์ด", tur: "Kart Anahtar Kelimeleri", zhs: "卡牌关键词" },

  // Badges
  "Badges":             { eng: "Badges", deu: "Abzeichen", esp: "Insignias", fra: "Badges", ita: "Distintivi", jpn: "バッジ", kor: "배지", pol: "Odznaki", ptb: "Distintivos", rus: "Значки", spa: "Insignias", tha: "แบดจ์", tur: "Rozetler", zhs: "徽章" },
  "Tiered Badges":      { eng: "Tiered Badges", deu: "Gestufte Abzeichen", esp: "Insignias por niveles", fra: "Badges à paliers", ita: "Distintivi a livelli", jpn: "階層バッジ", kor: "등급 배지", pol: "Odznaki wielopoziomowe", ptb: "Distintivos em níveis", rus: "Многоуровневые значки", spa: "Insignias por niveles", tha: "แบดจ์แบบขั้น", tur: "Kademeli Rozetler", zhs: "分级徽章" },
  "Single-Tier Badges": { eng: "Single-Tier Badges", deu: "Einstufige Abzeichen", esp: "Insignias de un solo nivel", fra: "Badges à palier unique", ita: "Distintivi a livello singolo", jpn: "単一バッジ", kor: "단일 등급 배지", pol: "Odznaki jednopoziomowe", ptb: "Distintivos de nível único", rus: "Одноуровневые значки", spa: "Insignias de un solo nivel", tha: "แบดจ์ขั้นเดียว", tur: "Tek Kademeli Rozetler", zhs: "单级徽章" },
  "Multiplayer-Only":   { eng: "Multiplayer-Only", deu: "Nur Mehrspieler", esp: "Solo multijugador", fra: "Multijoueur uniquement", ita: "Solo multigiocatore", jpn: "マルチプレイヤー専用", kor: "멀티플레이어 전용", pol: "Tylko wieloosobowe", ptb: "Apenas multijogador", rus: "Только мультиплеер", spa: "Solo multijugador", tha: "ผู้เล่นหลายคนเท่านั้น", tur: "Yalnızca Çok Oyunculu", zhs: "仅多人游戏" },
  "Tiers":              { eng: "Tiers", deu: "Stufen", esp: "Niveles", fra: "Paliers", ita: "Livelli", jpn: "階層", kor: "등급", pol: "Poziomy", ptb: "Níveis", rus: "Уровни", spa: "Niveles", tha: "ขั้น", tur: "Kademeler", zhs: "等级" },
  "Bronze":             { eng: "Bronze", deu: "Bronze", esp: "Bronce", fra: "Bronze", ita: "Bronzo", jpn: "ブロンズ", kor: "브론즈", pol: "Brąz", ptb: "Bronze", rus: "Бронза", spa: "Bronce", tha: "บรอนซ์", tur: "Bronz", zhs: "铜" },
  "Silver":             { eng: "Silver", deu: "Silber", esp: "Plata", fra: "Argent", ita: "Argento", jpn: "シルバー", kor: "실버", pol: "Srebro", ptb: "Prata", rus: "Серебро", spa: "Plata", tha: "ซิลเวอร์", tur: "Gümüş", zhs: "银" },
  "Gold tier":          { eng: "Gold", deu: "Gold", esp: "Oro", fra: "Or", ita: "Oro", jpn: "ゴールド", kor: "골드", pol: "Złoto", ptb: "Ouro", rus: "Золото", spa: "Oro", tha: "โกลด์", tur: "Altın", zhs: "金" },
  "Single tier":        { eng: "Single tier", deu: "Einzelne Stufe", esp: "Un nivel", fra: "Palier unique", ita: "Livello singolo", jpn: "単一階層", kor: "단일 등급", pol: "Jeden poziom", ptb: "Nível único", rus: "Один уровень", spa: "Un nivel", tha: "ขั้นเดียว", tur: "Tek kademe", zhs: "单级" },
  "Requires win":       { eng: "Requires win", deu: "Sieg erforderlich", esp: "Requiere victoria", fra: "Nécessite une victoire", ita: "Richiede una vittoria", jpn: "勝利が必要", kor: "승리 필요", pol: "Wymaga wygranej", ptb: "Requer vitória", rus: "Требуется победа", spa: "Requiere victoria", tha: "ต้องชนะ", tur: "Galibiyet gerekli", zhs: "需要胜利" },
  "Multiplayer only":   { eng: "Multiplayer only", deu: "Nur Mehrspieler", esp: "Solo multijugador", fra: "Multijoueur uniquement", ita: "Solo multigiocatore", jpn: "マルチプレイヤー専用", kor: "멀티플레이어 전용", pol: "Tylko wieloosobowe", ptb: "Apenas multijogador", rus: "Только мультиплеер", spa: "Solo multijugador", tha: "ผู้เล่นหลายคนเท่านั้น", tur: "Yalnızca çok oyunculu", zhs: "仅多人游戏" },
  "tier":               { eng: "tier", deu: "Stufe", esp: "nivel", fra: "palier", ita: "livello", jpn: "階層", kor: "등급", pol: "poziom", ptb: "nível", rus: "уровень", spa: "nivel", tha: "ขั้น", tur: "kademe", zhs: "级" },
  "tiers":              { eng: "tiers", deu: "Stufen", esp: "niveles", fra: "paliers", ita: "livelli", jpn: "階層", kor: "등급", pol: "poziomy", ptb: "níveis", rus: "уровней", spa: "niveles", tha: "ขั้น", tur: "kademe", zhs: "级" },
  "requires win":       { eng: "requires win", deu: "Sieg erforderlich", esp: "requiere victoria", fra: "nécessite une victoire", ita: "richiede una vittoria", jpn: "勝利が必要", kor: "승리 필요", pol: "wymaga wygranej", ptb: "requer vitória", rus: "требуется победа", spa: "requiere victoria", tha: "ต้องชนะ", tur: "galibiyet gerekli", zhs: "需要胜利" },
  "multiplayer only":   { eng: "multiplayer only", deu: "nur Mehrspieler", esp: "solo multijugador", fra: "multijoueur uniquement", ita: "solo multigiocatore", jpn: "マルチプレイヤー専用", kor: "멀티플레이어 전용", pol: "tylko wieloosobowe", ptb: "apenas multijogador", rus: "только мультиплеер", spa: "solo multijugador", tha: "ผู้เล่นหลายคนเท่านั้น", tur: "yalnızca çok oyunculu", zhs: "仅多人" },
  "Back to Badges":     { eng: "Back to Badges", deu: "Zurück zu Abzeichen", esp: "Volver a Insignias", fra: "Retour aux Badges", ita: "Torna ai Distintivi", jpn: "バッジに戻る", kor: "배지로 돌아가기", pol: "Powrót do Odznak", ptb: "Voltar para Distintivos", rus: "Назад к Значкам", spa: "Volver a Insignias", tha: "กลับไปที่แบดจ์", tur: "Rozetlere geri dön", zhs: "返回徽章" },
  "badges_tagline":     { eng: "Run-end badges are mini-achievements awarded on the Game Over screen. Some have Bronze / Silver / Gold tiers; a handful are only attainable in multiplayer. Badges contribute to your Daily Leaderboard score.", deu: "Run-Ende-Abzeichen sind Mini-Erfolge, die auf dem Game-Over-Bildschirm vergeben werden. Einige haben Bronze-/Silber-/Goldstufen; einige sind nur im Mehrspieler erreichbar. Abzeichen zählen zu deinem täglichen Bestenlisten-Score.", esp: "Las insignias de fin de partida son mini-logros otorgados en la pantalla de Game Over. Algunas tienen niveles Bronce/Plata/Oro; unas pocas solo se consiguen en multijugador. Las insignias cuentan para tu puntuación en la clasificación diaria.", fra: "Les badges de fin de partie sont des mini-succès accordés sur l'écran de Game Over. Certains ont des paliers Bronze/Argent/Or ; quelques-uns ne sont obtenables qu'en multijoueur. Les badges contribuent à votre score du classement quotidien.", ita: "I distintivi di fine partita sono mini-obiettivi assegnati nella schermata di Game Over. Alcuni hanno livelli Bronzo/Argento/Oro; alcuni sono ottenibili solo in multigiocatore. I distintivi contribuiscono al tuo punteggio nella classifica giornaliera.", jpn: "ラン終了バッジはゲームオーバー画面で獲得するミニ実績です。ブロンズ/シルバー/ゴールド階層を持つものや、マルチプレイヤー専用のものがあります。バッジはデイリーリーダーボードのスコアに加算されます。", kor: "런 종료 배지는 게임 오버 화면에서 획득하는 미니 업적입니다. 일부는 브론즈/실버/골드 등급을 가지며, 일부는 멀티플레이어에서만 얻을 수 있습니다. 배지는 일일 리더보드 점수에 반영됩니다.", pol: "Odznaki końca rozgrywki to mini-osiągnięcia przyznawane na ekranie Game Over. Niektóre mają poziomy Brąz/Srebro/Złoto; kilka można zdobyć tylko w trybie wieloosobowym. Odznaki wpływają na Twój wynik w Dziennym Rankingu.", ptb: "Distintivos de fim de jornada são mini-conquistas concedidas na tela de Game Over. Alguns têm níveis Bronze/Prata/Ouro; alguns só podem ser obtidos no multijogador. Distintivos contribuem para sua pontuação na classificação diária.", rus: "Значки конца забега — мини-достижения, выдаваемые на экране Game Over. У некоторых есть уровни Бронза/Серебро/Золото; часть доступна только в мультиплеере. Значки влияют на ваш счёт в ежедневном рейтинге.", spa: "Las insignias de fin de partida son mini-logros otorgados en la pantalla de Game Over. Algunas tienen niveles Bronce/Plata/Oro; unas pocas solo se consiguen en multijugador. Las insignias cuentan para tu puntuación en la clasificación diaria.", tha: "แบดจ์จบรันเป็นมินิอะชีฟเมนต์ที่มอบให้บนหน้าจอ Game Over บางอย่างมีขั้น Bronze/Silver/Gold บางส่วนได้เฉพาะในโหมดผู้เล่นหลายคน แบดจ์มีผลต่อคะแนน Daily Leaderboard", tur: "Tur sonu rozetleri, Game Over ekranında verilen mini başarımlardır. Bazılarının Bronz/Gümüş/Altın kademeleri vardır; birkaçı yalnızca çok oyunculu modda kazanılabilir. Rozetler, Günlük Liderlik Tablosu puanınıza katkıda bulunur.", zhs: "局末徽章是在游戏结束画面授予的小成就。一些有铜/银/金等级；部分仅在多人模式中可获得。徽章会计入你的每日排行榜得分。" },
  "multiplayer_only_tagline": { eng: "These badges can only be earned in multiplayer runs.", deu: "Diese Abzeichen können nur in Mehrspieler-Runs verdient werden.", esp: "Estas insignias solo pueden obtenerse en partidas multijugador.", fra: "Ces badges ne peuvent être obtenus qu'en parties multijoueur.", ita: "Questi distintivi possono essere ottenuti solo nelle partite multigiocatore.", jpn: "これらのバッジはマルチプレイヤーランでのみ獲得できます。", kor: "이 배지는 멀티플레이어 런에서만 획득할 수 있습니다.", pol: "Te odznaki można zdobyć tylko w rozgrywkach wieloosobowych.", ptb: "Estes distintivos só podem ser obtidos em partidas multijogador.", rus: "Эти значки можно получить только в мультиплеерных забегах.", spa: "Estas insignias solo pueden obtenerse en partidas multijugador.", tha: "แบดจ์เหล่านี้ได้เฉพาะในรันโหมดผู้เล่นหลายคน", tur: "Bu rozetler yalnızca çok oyunculu turlarda kazanılabilir.", zhs: "这些徽章仅可在多人模式中获得。" },

  // Leaderboards / runs
  "Leaderboards":       { eng: "Leaderboards", deu: "Bestenlisten", esp: "Clasificaciones", fra: "Classements", ita: "Classifiche", jpn: "リーダーボード", kor: "리더보드", pol: "Rankingi", ptb: "Classificações", rus: "Таблицы лидеров", spa: "Clasificaciones", tha: "ลีดเดอร์บอร์ด", tur: "Liderlik Tabloları", zhs: "排行榜" },
  "leaderboards_tagline": { eng: "Fastest wins and highest ascensions from the community. Browse every submitted run or drill into a specific character.", deu: "Schnellste Siege und höchste Aufstiege aus der Community. Alle eingereichten Runs durchsuchen oder einen bestimmten Charakter erkunden.", esp: "Victorias más rápidas y ascensiones más altas de la comunidad. Explora cada partida enviada o profundiza en un personaje específico.", fra: "Victoires les plus rapides et ascensions les plus hautes de la communauté. Parcourez chaque run soumise ou concentrez-vous sur un personnage spécifique.", ita: "Vittorie più veloci e ascensioni più alte dalla community. Sfoglia ogni partita inviata o approfondisci un personaggio specifico.", jpn: "コミュニティの最速勝利と最高アセンション。投稿された全ランを閲覧、または特定キャラクターを深掘り。", kor: "커뮤니티의 최단 승리와 최고 승천. 제출된 모든 런을 탐색하거나 특정 캐릭터를 깊이 살펴보세요.", pol: "Najszybsze zwycięstwa i najwyższe ascensje ze społeczności. Przeglądaj każdą zgłoszoną rozgrywkę lub zagłęb się w konkretną postać.", ptb: "Vitórias mais rápidas e maiores ascensões da comunidade. Navegue por cada partida enviada ou aprofunde-se em um personagem específico.", rus: "Самые быстрые победы и высшие восхождения сообщества. Просматривайте каждый отправленный забег или углубляйтесь в конкретного персонажа.", spa: "Victorias más rápidas y ascensiones más altas de la comunidad. Explora cada partida enviada o profundiza en un personaje específico.", tha: "ชัยชนะที่เร็วที่สุดและ Ascension สูงสุดจากชุมชน เรียกดูรันที่ส่งมาทั้งหมดหรือเจาะลึกตัวละครเฉพาะ", tur: "Topluluktan en hızlı galibiyetler ve en yüksek yükselmeler. Gönderilen her turu inceleyin veya belirli bir karaktere odaklanın.", zhs: "来自社区的最快胜利和最高登塔。浏览每个提交的对局或深入查看特定角色。" },
  "Fastest Wins":       { eng: "Fastest Wins", deu: "Schnellste Siege", esp: "Victorias más rápidas", fra: "Victoires les plus rapides", ita: "Vittorie più veloci", jpn: "最速勝利", kor: "최단 승리", pol: "Najszybsze zwycięstwa", ptb: "Vitórias mais rápidas", rus: "Самые быстрые победы", spa: "Victorias más rápidas", tha: "ชัยชนะเร็วที่สุด", tur: "En Hızlı Galibiyetler", zhs: "最快胜利" },
  "Highest Ascension":  { eng: "Highest Ascension", deu: "Höchster Aufstieg", esp: "Ascensión más alta", fra: "Ascension la plus haute", ita: "Ascensione più alta", jpn: "最高アセンション", kor: "최고 승천", pol: "Najwyższa ascensja", ptb: "Maior ascensão", rus: "Высшее восхождение", spa: "Ascensión más alta", tha: "Ascension สูงสุด", tur: "En Yüksek Yükselme", zhs: "最高登塔" },
  "Browse Runs":        { eng: "Browse Runs", deu: "Runs durchsuchen", esp: "Explorar partidas", fra: "Parcourir les runs", ita: "Sfoglia partite", jpn: "ラン一覧", kor: "런 탐색", pol: "Przeglądaj rozgrywki", ptb: "Navegar partidas", rus: "Обзор забегов", spa: "Explorar partidas", tha: "เรียกดูรัน", tur: "Turları İncele", zhs: "浏览对局" },
  "Fastest":            { eng: "Fastest", deu: "Am schnellsten", esp: "Más rápido", fra: "Plus rapide", ita: "Più veloci", jpn: "最速", kor: "최단", pol: "Najszybsze", ptb: "Mais rápidas", rus: "Самые быстрые", spa: "Más rápido", tha: "เร็วที่สุด", tur: "En Hızlı", zhs: "最快" },
  "Browse":             { eng: "Browse", deu: "Durchsuchen", esp: "Explorar", fra: "Parcourir", ita: "Sfoglia", jpn: "閲覧", kor: "탐색", pol: "Przeglądaj", ptb: "Navegar", rus: "Обзор", spa: "Explorar", tha: "เรียกดู", tur: "İncele", zhs: "浏览" },
  "Ascension":          { eng: "Ascension", deu: "Aufstieg", esp: "Ascensión", fra: "Ascension", ita: "Ascensione", jpn: "アセンション", kor: "승천", pol: "Ascensja", ptb: "Ascensão", rus: "Восхождение", spa: "Ascensión", tha: "Ascension", tur: "Yükselme", zhs: "登塔" },
  "Anonymous":          { eng: "Anonymous", deu: "Anonym", esp: "Anónimo", fra: "Anonyme", ita: "Anonimo", jpn: "匿名", kor: "익명", pol: "Anonim", ptb: "Anônimo", rus: "Аноним", spa: "Anónimo", tha: "ไม่ระบุชื่อ", tur: "Anonim", zhs: "匿名" },
  "View run":           { eng: "View run", deu: "Run ansehen", esp: "Ver partida", fra: "Voir la run", ita: "Vedi partita", jpn: "ランを見る", kor: "런 보기", pol: "Zobacz rozgrywkę", ptb: "Ver partida", rus: "Открыть забег", spa: "Ver partida", tha: "ดูรัน", tur: "Turu görüntüle", zhs: "查看对局" },
  "View run details":   { eng: "View run details", deu: "Run-Details ansehen", esp: "Ver detalles de partida", fra: "Voir les détails de la run", ita: "Dettagli partita", jpn: "ラン詳細を見る", kor: "런 상세 보기", pol: "Zobacz szczegóły rozgrywki", ptb: "Ver detalhes da partida", rus: "Детали забега", spa: "Ver detalles de partida", tha: "ดูรายละเอียดรัน", tur: "Tur detaylarını görüntüle", zhs: "查看对局详情" },
  "Username...":        { eng: "Username...", deu: "Benutzername...", esp: "Nombre de usuario...", fra: "Nom d'utilisateur...", ita: "Nome utente...", jpn: "ユーザー名...", kor: "사용자 이름...", pol: "Nazwa użytkownika...", ptb: "Nome de usuário...", rus: "Имя пользователя...", spa: "Nombre de usuario...", tha: "ชื่อผู้ใช้...", tur: "Kullanıcı adı...", zhs: "用户名..." },
  "Seed...":            { eng: "Seed...", deu: "Seed...", esp: "Semilla...", fra: "Seed...", ita: "Seed...", jpn: "シード...", kor: "시드...", pol: "Seed...", ptb: "Seed...", rus: "Сид...", spa: "Semilla...", tha: "ซีด...", tur: "Tohum...", zhs: "种子..." },
  "Search username...": { eng: "Search username...", deu: "Benutzername suchen...", esp: "Buscar nombre de usuario...", fra: "Rechercher un nom d'utilisateur...", ita: "Cerca nome utente...", jpn: "ユーザー名を検索...", kor: "사용자 이름 검색...", pol: "Szukaj nazwy użytkownika...", ptb: "Pesquisar nome de usuário...", rus: "Поиск имени пользователя...", spa: "Buscar nombre de usuario...", tha: "ค้นหาชื่อผู้ใช้...", tur: "Kullanıcı adı ara...", zhs: "搜索用户名..." },

  // Submit a Run
  "Submit a Run":       { eng: "Submit a Run", deu: "Run einreichen", esp: "Enviar partida", fra: "Soumettre une run", ita: "Invia partita", jpn: "ランを投稿", kor: "런 제출", pol: "Prześlij rozgrywkę", ptb: "Enviar partida", rus: "Отправить забег", spa: "Enviar partida", tha: "ส่งรัน", tur: "Tur Gönder", zhs: "提交对局" },
  "submit_tagline":     { eng: "Upload your .run files to contribute to leaderboards and community stats. Your .run files are parsed locally in your browser — nothing leaves your machine until you hit submit.", deu: "Lade deine .run-Dateien hoch, um zu den Bestenlisten und Community-Statistiken beizutragen. Deine .run-Dateien werden lokal im Browser verarbeitet — nichts verlässt deinen Rechner, bis du auf Einreichen klickst.", esp: "Sube tus archivos .run para contribuir a las clasificaciones y estadísticas de la comunidad. Tus archivos .run se procesan localmente en tu navegador — nada sale de tu máquina hasta que envías.", fra: "Téléversez vos fichiers .run pour contribuer aux classements et statistiques de la communauté. Vos fichiers .run sont analysés localement dans votre navigateur — rien ne quitte votre machine avant l'envoi.", ita: "Carica i tuoi file .run per contribuire alle classifiche e alle statistiche della community. I tuoi file .run vengono elaborati localmente nel browser — nulla lascia il tuo computer finché non invii.", jpn: ".runファイルをアップロードしてリーダーボードとコミュニティ統計に貢献しましょう。.runファイルはブラウザでローカル解析されます — 送信するまで何もあなたのマシンから出ません。", kor: ".run 파일을 업로드하여 리더보드와 커뮤니티 통계에 기여하세요. .run 파일은 브라우저에서 로컬로 파싱됩니다 — 제출을 누를 때까지 아무것도 기기를 벗어나지 않습니다.", pol: "Prześlij pliki .run, aby współtworzyć rankingi i statystyki społeczności. Pliki .run są parsowane lokalnie w przeglądarce — nic nie opuszcza Twojego komputera, dopóki nie klikniesz Prześlij.", ptb: "Envie seus arquivos .run para contribuir com as classificações e estatísticas da comunidade. Seus arquivos .run são processados localmente no navegador — nada sai da sua máquina até você clicar em enviar.", rus: "Загрузите файлы .run, чтобы внести вклад в таблицы лидеров и статистику сообщества. Файлы .run парсятся локально в браузере — ничего не покидает вашу машину до момента отправки.", spa: "Sube tus archivos .run para contribuir a las clasificaciones y estadísticas de la comunidad. Tus archivos .run se procesan localmente en tu navegador — nada sale de tu máquina hasta que envías.", tha: "อัปโหลดไฟล์ .run เพื่อสนับสนุนลีดเดอร์บอร์ดและสถิติชุมชน ไฟล์ .run จะถูกแยกวิเคราะห์ในเบราว์เซอร์ของคุณ — ไม่มีอะไรออกจากเครื่องจนกว่าคุณจะกดส่ง", tur: "Liderlik tablolarına ve topluluk istatistiklerine katkıda bulunmak için .run dosyalarınızı yükleyin. .run dosyalarınız tarayıcınızda yerel olarak ayrıştırılır — gönder butonuna basana kadar hiçbir şey makinenizden çıkmaz.", zhs: "上传你的 .run 文件为排行榜和社区统计做贡献。你的 .run 文件在浏览器本地解析 — 在点击提交之前不会离开你的设备。" },
  "Drag & drop .run files here, or click to select": { eng: "Drag & drop .run files here, or click to select", deu: ".run-Dateien hier ablegen oder zum Auswählen klicken", esp: "Arrastra archivos .run aquí, o haz clic para seleccionar", fra: "Glissez-déposez les fichiers .run ici, ou cliquez pour sélectionner", ita: "Trascina i file .run qui o clicca per selezionare", jpn: ".runファイルをドラッグ＆ドロップまたはクリックして選択", kor: ".run 파일을 끌어다 놓거나 클릭하여 선택", pol: "Przeciągnij pliki .run tutaj lub kliknij, aby wybrać", ptb: "Arraste arquivos .run aqui ou clique para selecionar", rus: "Перетащите файлы .run сюда или нажмите для выбора", spa: "Arrastra archivos .run aquí, o haz clic para seleccionar", tha: "ลากและวางไฟล์ .run ที่นี่ หรือคลิกเพื่อเลือก", tur: ".run dosyalarını buraya sürükleyin veya seçmek için tıklayın", zhs: "将 .run 文件拖放到此处，或点击选择" },
  "Drop files here...": { eng: "Drop files here...", deu: "Dateien hier ablegen...", esp: "Suelta archivos aquí...", fra: "Déposez les fichiers ici...", ita: "Rilascia i file qui...", jpn: "ここにファイルをドロップ...", kor: "여기에 파일을 놓으세요...", pol: "Upuść pliki tutaj...", ptb: "Solte os arquivos aqui...", rus: "Отпустите файлы здесь...", spa: "Suelta archivos aquí...", tha: "วางไฟล์ที่นี่...", tur: "Dosyaları buraya bırakın...", zhs: "在此处放下文件..." },
  "Username (optional)": { eng: "Username (optional)", deu: "Benutzername (optional)", esp: "Nombre de usuario (opcional)", fra: "Nom d'utilisateur (facultatif)", ita: "Nome utente (opzionale)", jpn: "ユーザー名（任意）", kor: "사용자 이름 (선택)", pol: "Nazwa użytkownika (opcjonalna)", ptb: "Nome de usuário (opcional)", rus: "Имя пользователя (необязательно)", spa: "Nombre de usuario (opcional)", tha: "ชื่อผู้ใช้ (ไม่บังคับ)", tur: "Kullanıcı adı (isteğe bağlı)", zhs: "用户名（可选）" },

  // Stats
  "Stats":              { eng: "Stats", deu: "Statistiken", esp: "Estadísticas", fra: "Statistiques", ita: "Statistiche", jpn: "統計", kor: "통계", pol: "Statystyki", ptb: "Estatísticas", rus: "Статистика", spa: "Estadísticas", tha: "สถิติ", tur: "İstatistikler", zhs: "统计" },
  "stats_tagline":      { eng: "Win rates by character, card pick rates, most common relics, deadliest encounters — computed from every submitted run.", deu: "Siegraten pro Charakter, Kartenauswahlraten, häufigste Relikte, tödlichste Begegnungen — aus jedem eingereichten Run berechnet.", esp: "Tasas de victoria por personaje, tasas de elección de cartas, reliquias más comunes, encuentros más letales — calculado a partir de cada partida enviada.", fra: "Taux de victoire par personnage, taux de sélection de cartes, reliques les plus communes, rencontres les plus mortelles — calculés à partir de chaque run soumise.", ita: "Tassi di vittoria per personaggio, tassi di scelta delle carte, reliquie più comuni, scontri più letali — calcolati da ogni partita inviata.", jpn: "キャラクター別勝率、カード選択率、最も一般的なレリック、最も危険なエンカウンター — 投稿された全ランから計算。", kor: "캐릭터별 승률, 카드 픽률, 가장 흔한 유물, 가장 위험한 조우 — 제출된 모든 런에서 계산.", pol: "Współczynniki zwycięstw według postaci, wskaźniki wyboru kart, najczęstsze relikty, najbardziej zabójcze spotkania — obliczane z każdej zgłoszonej rozgrywki.", ptb: "Taxas de vitória por personagem, taxas de escolha de cartas, relíquias mais comuns, encontros mais letais — calculados a partir de cada partida enviada.", rus: "Винрейты по персонажам, частота выбора карт, самые частые реликвии, самые смертоносные встречи — рассчитано по всем отправленным забегам.", spa: "Tasas de victoria por personaje, tasas de elección de cartas, reliquias más comunes, encuentros más letales — calculado a partir de cada partida enviada.", tha: "อัตราชนะตามตัวละคร อัตราการเลือกการ์ด เรลิกที่พบบ่อย การเผชิญหน้าที่อันตรายที่สุด — คำนวณจากทุกรันที่ส่งมา", tur: "Karakter başına kazanma oranları, kart seçim oranları, en yaygın kalıntılar, en ölümcül karşılaşmalar — gönderilen her turdan hesaplanır.", zhs: "按角色的胜率、卡牌选择率、最常见遗物、最致命遭遇 — 从每个提交的对局计算。" },

  // Runs / Run Summary
  "runs_tagline":       { eng: "Community runs browser — view seeds, build IDs, final decks, and shared runs from across the playerbase.", deu: "Community-Run-Browser — Seeds, Build-IDs, finale Decks und geteilte Runs aus der Spielerschaft ansehen.", esp: "Navegador de partidas de la comunidad — consulta semillas, IDs de build, mazos finales y partidas compartidas de toda la base de jugadores.", fra: "Navigateur de runs communautaires — consultez les seeds, IDs de build, decks finaux et runs partagées de toute la base de joueurs.", ita: "Browser delle partite della community — visualizza seed, ID build, deck finali e partite condivise da tutta la base giocatori.", jpn: "コミュニティランブラウザ — シード、ビルドID、最終デッキ、プレイヤー全体から共有されたランを閲覧。", kor: "커뮤니티 런 브라우저 — 시드, 빌드 ID, 최종 덱, 플레이어베이스 전체에서 공유된 런을 확인하세요.", pol: "Przeglądarka rozgrywek społeczności — zobacz seedy, ID buildów, finalne talie i udostępnione rozgrywki z całej bazy graczy.", ptb: "Navegador de partidas da comunidade — veja seeds, IDs de build, decks finais e partidas compartilhadas de toda a base de jogadores.", rus: "Браузер забегов сообщества — просматривайте сиды, build ID, финальные колоды и опубликованные забеги со всей базы игроков.", spa: "Navegador de partidas de la comunidad — consulta semillas, IDs de build, mazos finales y partidas compartidas de toda la base de jugadores.", tha: "เบราว์เซอร์รันชุมชน — ดูซีด build ID เด็คสุดท้าย และรันที่แชร์จากผู้เล่นทั้งหมด", tur: "Topluluk turları gezgini — seed'leri, build ID'leri, son desteleri ve oyuncu tabanından paylaşılan turları görüntüleyin.", zhs: "社区对局浏览器 — 查看种子、版本 ID、最终牌组，以及整个玩家群体分享的对局。" },
  "Victory":            { eng: "Victory", deu: "Sieg", esp: "Victoria", fra: "Victoire", ita: "Vittoria", jpn: "勝利", kor: "승리", pol: "Zwycięstwo", ptb: "Vitória", rus: "Победа", spa: "Victoria", tha: "ชนะ", tur: "Galibiyet", zhs: "胜利" },
  "Defeat":             { eng: "Defeat", deu: "Niederlage", esp: "Derrota", fra: "Défaite", ita: "Sconfitta", jpn: "敗北", kor: "패배", pol: "Porażka", ptb: "Derrota", rus: "Поражение", spa: "Derrota", tha: "แพ้", tur: "Yenilgi", zhs: "失败" },
  "Abandoned":          { eng: "Abandoned", deu: "Abgebrochen", esp: "Abandonada", fra: "Abandonnée", ita: "Abbandonata", jpn: "放棄", kor: "중단", pol: "Porzucona", ptb: "Abandonada", rus: "Брошен", spa: "Abandonada", tha: "ละทิ้ง", tur: "Terk edilmiş", zhs: "已放弃" },
  "Share Run":          { eng: "Share Run", deu: "Run teilen", esp: "Compartir partida", fra: "Partager la run", ita: "Condividi partita", jpn: "ランを共有", kor: "런 공유", pol: "Udostępnij rozgrywkę", ptb: "Compartilhar partida", rus: "Поделиться забегом", spa: "Compartir partida", tha: "แชร์รัน", tur: "Turu paylaş", zhs: "分享对局" },
  "Copied!":            { eng: "Copied!", deu: "Kopiert!", esp: "¡Copiado!", fra: "Copié !", ita: "Copiato!", jpn: "コピーしました！", kor: "복사됨!", pol: "Skopiowano!", ptb: "Copiado!", rus: "Скопировано!", spa: "¡Copiado!", tha: "คัดลอกแล้ว!", tur: "Kopyalandı!", zhs: "已复制！" },
  "The journey ended.": { eng: "The journey ended.", deu: "Die Reise endete.", esp: "El viaje terminó.", fra: "Le voyage s'est terminé.", ita: "Il viaggio è finito.", jpn: "旅は終わった。", kor: "여정이 끝났습니다.", pol: "Podróż dobiegła końca.", ptb: "A jornada terminou.", rus: "Путешествие завершилось.", spa: "El viaje terminó.", tha: "การเดินทางจบลงแล้ว", tur: "Yolculuk sona erdi.", zhs: "旅程结束了。" },
  "Unknown":            { eng: "Unknown", deu: "Unbekannt", esp: "Desconocido", fra: "Inconnu", ita: "Sconosciuto", jpn: "不明", kor: "알 수 없음", pol: "Nieznany", ptb: "Desconhecido", rus: "Неизвестно", spa: "Desconocido", tha: "ไม่ทราบ", tur: "Bilinmiyor", zhs: "未知" },
  "Common":             { eng: "Common", deu: "Gewöhnlich", esp: "Común", fra: "Commun", ita: "Comune", jpn: "コモン", kor: "일반", pol: "Powszechny", ptb: "Comum", rus: "Обычный", spa: "Común", tha: "ธรรมดา", tur: "Yaygın", zhs: "普通" },
  "Uncommon":           { eng: "Uncommon", deu: "Ungewöhnlich", esp: "Poco común", fra: "Peu commun", ita: "Non comune", jpn: "アンコモン", kor: "고급", pol: "Niepowszechny", ptb: "Incomum", rus: "Необычный", spa: "Poco común", tha: "ไม่ธรรมดา", tur: "Nadir", zhs: "罕见" },
  "Rare":               { eng: "Rare", deu: "Selten", esp: "Raro", fra: "Rare", ita: "Raro", jpn: "レア", kor: "희귀", pol: "Rzadki", ptb: "Raro", rus: "Редкий", spa: "Raro", tha: "หายาก", tur: "Nadide", zhs: "稀有" },
  "Ancient":            { eng: "Ancient", deu: "Uralt", esp: "Ancestral", fra: "Ancestral", ita: "Antico", jpn: "エンシェント", kor: "고대", pol: "Pradawny", ptb: "Ancestral", rus: "Древний", spa: "Ancestral", tha: "โบราณ", tur: "Kadim", zhs: "远古" },
  "Standard":           { eng: "Standard", deu: "Standard", esp: "Estándar", fra: "Standard", ita: "Standard", jpn: "スタンダード", kor: "스탠다드", pol: "Standardowy", ptb: "Padrão", rus: "Стандартный", spa: "Estándar", tha: "สแตนดาร์ด", tur: "Standart", zhs: "标准" },
  "Starter":            { eng: "Starter", deu: "Start", esp: "Inicial", fra: "Départ", ita: "Iniziale", jpn: "スターター", kor: "시작", pol: "Startowy", ptb: "Inicial", rus: "Стартовый", spa: "Inicial", tha: "เริ่มต้น", tur: "Başlangıç", zhs: "初始" },
  "Status":             { eng: "Status", deu: "Status", esp: "Estado", fra: "Statut", ita: "Stato", jpn: "ステータス", kor: "상태", pol: "Status", ptb: "Status", rus: "Статус", spa: "Estado", tha: "สถานะ", tur: "Durum", zhs: "状态" },
};

/**
 * Get a translated UI string.
 * Keys are the English display text (e.g., "Back to", "Overview").
 */
export function t(key: string, lang: string): string {
  const entry = UI[key];
  if (!entry) return key;
  return entry[lang] || entry.eng || key;
}
